// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2026_1_TheBugs/internal/usecase/dto"
	tokens "github.com/go-park-mail-ru/2026_1_TheBugs/internal/usecase/jwt"
	gomock "github.com/golang/mock/gomock"
)

// MockAuthUseCase is a mock of AuthUseCase interface.
type MockAuthUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAuthUseCaseMockRecorder
}

// MockAuthUseCaseMockRecorder is the mock recorder for MockAuthUseCase.
type MockAuthUseCaseMockRecorder struct {
	mock *MockAuthUseCase
}

// NewMockAuthUseCase creates a new mock instance.
func NewMockAuthUseCase(ctrl *gomock.Controller) *MockAuthUseCase {
	mock := &MockAuthUseCase{ctrl: ctrl}
	mock.recorder = &MockAuthUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthUseCase) EXPECT() *MockAuthUseCaseMockRecorder {
	return m.recorder
}

// CheckRecoveryCode mocks base method.
func (m *MockAuthUseCase) CheckRecoveryCode(ctx context.Context, sessionID, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRecoveryCode", ctx, sessionID, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckRecoveryCode indicates an expected call of CheckRecoveryCode.
func (mr *MockAuthUseCaseMockRecorder) CheckRecoveryCode(ctx, sessionID, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRecoveryCode", reflect.TypeOf((*MockAuthUseCase)(nil).CheckRecoveryCode), ctx, sessionID, code)
}

// LoginUseCase mocks base method.
func (m *MockAuthUseCase) LoginUseCase(ctx context.Context, email, password string) (*dto.UserAccessCredDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUseCase", ctx, email, password)
	ret0, _ := ret[0].(*dto.UserAccessCredDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUseCase indicates an expected call of LoginUseCase.
func (mr *MockAuthUseCaseMockRecorder) LoginUseCase(ctx, email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUseCase", reflect.TypeOf((*MockAuthUseCase)(nil).LoginUseCase), ctx, email, password)
}

// LoginUserFromVKUseCase mocks base method.
func (m *MockAuthUseCase) LoginUserFromVKUseCase(ctx context.Context, flow dto.OAuthCodeFlow) (*dto.UserAccessCredDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUserFromVKUseCase", ctx, flow)
	ret0, _ := ret[0].(*dto.UserAccessCredDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUserFromVKUseCase indicates an expected call of LoginUserFromVKUseCase.
func (mr *MockAuthUseCaseMockRecorder) LoginUserFromVKUseCase(ctx, flow interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUserFromVKUseCase", reflect.TypeOf((*MockAuthUseCase)(nil).LoginUserFromVKUseCase), ctx, flow)
}

// LoginUserFromYandexUseCase mocks base method.
func (m *MockAuthUseCase) LoginUserFromYandexUseCase(ctx context.Context, flow dto.OAuthCodeFlow) (*dto.UserAccessCredDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUserFromYandexUseCase", ctx, flow)
	ret0, _ := ret[0].(*dto.UserAccessCredDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUserFromYandexUseCase indicates an expected call of LoginUserFromYandexUseCase.
func (mr *MockAuthUseCaseMockRecorder) LoginUserFromYandexUseCase(ctx, flow interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUserFromYandexUseCase", reflect.TypeOf((*MockAuthUseCase)(nil).LoginUserFromYandexUseCase), ctx, flow)
}

// LogoutUseCase mocks base method.
func (m *MockAuthUseCase) LogoutUseCase(ctx context.Context, logoutCred dto.LogoutDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogoutUseCase", ctx, logoutCred)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogoutUseCase indicates an expected call of LogoutUseCase.
func (mr *MockAuthUseCaseMockRecorder) LogoutUseCase(ctx, logoutCred interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogoutUseCase", reflect.TypeOf((*MockAuthUseCase)(nil).LogoutUseCase), ctx, logoutCred)
}

// RefreshTokenUseCase mocks base method.
func (m *MockAuthUseCase) RefreshTokenUseCase(ctx context.Context, refreshToken string) (*dto.UserAccessCredDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTokenUseCase", ctx, refreshToken)
	ret0, _ := ret[0].(*dto.UserAccessCredDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshTokenUseCase indicates an expected call of RefreshTokenUseCase.
func (mr *MockAuthUseCaseMockRecorder) RefreshTokenUseCase(ctx, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTokenUseCase", reflect.TypeOf((*MockAuthUseCase)(nil).RefreshTokenUseCase), ctx, refreshToken)
}

// RegisterUseCase mocks base method.
func (m *MockAuthUseCase) RegisterUseCase(ctx context.Context, data dto.CreateUserDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUseCase", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterUseCase indicates an expected call of RegisterUseCase.
func (mr *MockAuthUseCaseMockRecorder) RegisterUseCase(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUseCase", reflect.TypeOf((*MockAuthUseCase)(nil).RegisterUseCase), ctx, data)
}

// SendRecoveryCode mocks base method.
func (m *MockAuthUseCase) SendRecoveryCode(ctx context.Context, email string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendRecoveryCode", ctx, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendRecoveryCode indicates an expected call of SendRecoveryCode.
func (mr *MockAuthUseCaseMockRecorder) SendRecoveryCode(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendRecoveryCode", reflect.TypeOf((*MockAuthUseCase)(nil).SendRecoveryCode), ctx, email)
}

// SendVerificationEmailCode mocks base method.
func (m *MockAuthUseCase) SendVerificationEmailCode(ctx context.Context, email string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendVerificationEmailCode", ctx, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendVerificationEmailCode indicates an expected call of SendVerificationEmailCode.
func (mr *MockAuthUseCaseMockRecorder) SendVerificationEmailCode(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVerificationEmailCode", reflect.TypeOf((*MockAuthUseCase)(nil).SendVerificationEmailCode), ctx, email)
}

// UpdateUserPassword mocks base method.
func (m *MockAuthUseCase) UpdateUserPassword(ctx context.Context, sessionID, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPassword", ctx, sessionID, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPassword indicates an expected call of UpdateUserPassword.
func (mr *MockAuthUseCaseMockRecorder) UpdateUserPassword(ctx, sessionID, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPassword", reflect.TypeOf((*MockAuthUseCase)(nil).UpdateUserPassword), ctx, sessionID, password)
}

// ValidateAccessToken mocks base method.
func (m *MockAuthUseCase) ValidateAccessToken(ctx context.Context, accessToken string) (*tokens.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", ctx, accessToken)
	ret0, _ := ret[0].(*tokens.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MockAuthUseCaseMockRecorder) ValidateAccessToken(ctx, accessToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MockAuthUseCase)(nil).ValidateAccessToken), ctx, accessToken)
}

// VerifyUserEmail mocks base method.
func (m *MockAuthUseCase) VerifyUserEmail(ctx context.Context, sessionID, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUserEmail", ctx, sessionID, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyUserEmail indicates an expected call of VerifyUserEmail.
func (mr *MockAuthUseCaseMockRecorder) VerifyUserEmail(ctx, sessionID, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUserEmail", reflect.TypeOf((*MockAuthUseCase)(nil).VerifyUserEmail), ctx, sessionID, code)
}

// MockUserUseCase is a mock of UserUseCase interface.
type MockUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUserUseCaseMockRecorder
}

// MockUserUseCaseMockRecorder is the mock recorder for MockUserUseCase.
type MockUserUseCaseMockRecorder struct {
	mock *MockUserUseCase
}

// NewMockUserUseCase creates a new mock instance.
func NewMockUserUseCase(ctrl *gomock.Controller) *MockUserUseCase {
	mock := &MockUserUseCase{ctrl: ctrl}
	mock.recorder = &MockUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserUseCase) EXPECT() *MockUserUseCaseMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockUserUseCase) GetByID(ctx context.Context, userID int) (*dto.UserDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, userID)
	ret0, _ := ret[0].(*dto.UserDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserUseCaseMockRecorder) GetByID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserUseCase)(nil).GetByID), ctx, userID)
}

// UpdateProfile mocks base method.
func (m *MockUserUseCase) UpdateProfile(ctx context.Context, data dto.UpdateProfileRequest) (*dto.UserDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, data)
	ret0, _ := ret[0].(*dto.UserDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockUserUseCaseMockRecorder) UpdateProfile(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockUserUseCase)(nil).UpdateProfile), ctx, data)
}
