// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_TheBugs/internal/delivery/grpc/generated/auth (interfaces: AuthServiceClient)

// Package grpc_client is a generated GoMock package.
package grpc_client

import (
	context "context"
	reflect "reflect"

	auth "github.com/go-park-mail-ru/2026_1_TheBugs/internal/delivery/grpc/generated/auth"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockAuthServiceClient is a mock of AuthServiceClient interface.
type MockAuthServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceClientMockRecorder
}

// MockAuthServiceClientMockRecorder is the mock recorder for MockAuthServiceClient.
type MockAuthServiceClientMockRecorder struct {
	mock *MockAuthServiceClient
}

// NewMockAuthServiceClient creates a new mock instance.
func NewMockAuthServiceClient(ctrl *gomock.Controller) *MockAuthServiceClient {
	mock := &MockAuthServiceClient{ctrl: ctrl}
	mock.recorder = &MockAuthServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServiceClient) EXPECT() *MockAuthServiceClientMockRecorder {
	return m.recorder
}

// CheckAccessToken mocks base method.
func (m *MockAuthServiceClient) CheckAccessToken(arg0 context.Context, arg1 *auth.CheckAccessTokenRequest, arg2 ...grpc.CallOption) (*auth.CheckAccessTokenResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckAccessToken", varargs...)
	ret0, _ := ret[0].(*auth.CheckAccessTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAccessToken indicates an expected call of CheckAccessToken.
func (mr *MockAuthServiceClientMockRecorder) CheckAccessToken(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAccessToken", reflect.TypeOf((*MockAuthServiceClient)(nil).CheckAccessToken), varargs...)
}

// LoginUser mocks base method.
func (m *MockAuthServiceClient) LoginUser(arg0 context.Context, arg1 *auth.LoginUserRequest, arg2 ...grpc.CallOption) (*auth.LoginResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LoginUser", varargs...)
	ret0, _ := ret[0].(*auth.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockAuthServiceClientMockRecorder) LoginUser(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockAuthServiceClient)(nil).LoginUser), varargs...)
}

// Logout mocks base method.
func (m *MockAuthServiceClient) Logout(arg0 context.Context, arg1 *auth.LogoutRequest, arg2 ...grpc.CallOption) (*auth.StatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Logout", varargs...)
	ret0, _ := ret[0].(*auth.StatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceClientMockRecorder) Logout(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthServiceClient)(nil).Logout), varargs...)
}

// RefreshToken mocks base method.
func (m *MockAuthServiceClient) RefreshToken(arg0 context.Context, arg1 *auth.RefreshTokenRequest, arg2 ...grpc.CallOption) (*auth.LoginResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RefreshToken", varargs...)
	ret0, _ := ret[0].(*auth.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockAuthServiceClientMockRecorder) RefreshToken(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockAuthServiceClient)(nil).RefreshToken), varargs...)
}

// RegisterUser mocks base method.
func (m *MockAuthServiceClient) RegisterUser(arg0 context.Context, arg1 *auth.RegisterUserRequest, arg2 ...grpc.CallOption) (*auth.StatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterUser", varargs...)
	ret0, _ := ret[0].(*auth.StatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockAuthServiceClientMockRecorder) RegisterUser(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockAuthServiceClient)(nil).RegisterUser), varargs...)
}

// SendCodeOnEmail mocks base method.
func (m *MockAuthServiceClient) SendCodeOnEmail(arg0 context.Context, arg1 *auth.SendCodeOnEmailRequest, arg2 ...grpc.CallOption) (*auth.SessionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendCodeOnEmail", varargs...)
	ret0, _ := ret[0].(*auth.SessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendCodeOnEmail indicates an expected call of SendCodeOnEmail.
func (mr *MockAuthServiceClientMockRecorder) SendCodeOnEmail(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCodeOnEmail", reflect.TypeOf((*MockAuthServiceClient)(nil).SendCodeOnEmail), varargs...)
}

// SendVerifyCodeOnEmail mocks base method.
func (m *MockAuthServiceClient) SendVerifyCodeOnEmail(arg0 context.Context, arg1 *auth.SendVerifyCodeOnEmailRequest, arg2 ...grpc.CallOption) (*auth.SessionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendVerifyCodeOnEmail", varargs...)
	ret0, _ := ret[0].(*auth.SessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendVerifyCodeOnEmail indicates an expected call of SendVerifyCodeOnEmail.
func (mr *MockAuthServiceClientMockRecorder) SendVerifyCodeOnEmail(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVerifyCodeOnEmail", reflect.TypeOf((*MockAuthServiceClient)(nil).SendVerifyCodeOnEmail), varargs...)
}

// UpdatePassword mocks base method.
func (m *MockAuthServiceClient) UpdatePassword(arg0 context.Context, arg1 *auth.UpdatePasswordRequest, arg2 ...grpc.CallOption) (*auth.StatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdatePassword", varargs...)
	ret0, _ := ret[0].(*auth.StatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockAuthServiceClientMockRecorder) UpdatePassword(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockAuthServiceClient)(nil).UpdatePassword), varargs...)
}

// VKLogin mocks base method.
func (m *MockAuthServiceClient) VKLogin(arg0 context.Context, arg1 *auth.VKLoginRequest, arg2 ...grpc.CallOption) (*auth.LoginResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "VKLogin", varargs...)
	ret0, _ := ret[0].(*auth.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VKLogin indicates an expected call of VKLogin.
func (mr *MockAuthServiceClientMockRecorder) VKLogin(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VKLogin", reflect.TypeOf((*MockAuthServiceClient)(nil).VKLogin), varargs...)
}

// VerifyCode mocks base method.
func (m *MockAuthServiceClient) VerifyCode(arg0 context.Context, arg1 *auth.VerifyCodeRequest, arg2 ...grpc.CallOption) (*auth.StatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "VerifyCode", varargs...)
	ret0, _ := ret[0].(*auth.StatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyCode indicates an expected call of VerifyCode.
func (mr *MockAuthServiceClientMockRecorder) VerifyCode(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyCode", reflect.TypeOf((*MockAuthServiceClient)(nil).VerifyCode), varargs...)
}

// VerifyRecoveryCode mocks base method.
func (m *MockAuthServiceClient) VerifyRecoveryCode(arg0 context.Context, arg1 *auth.VerifyRecoveryCodeRequest, arg2 ...grpc.CallOption) (*auth.StatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "VerifyRecoveryCode", varargs...)
	ret0, _ := ret[0].(*auth.StatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyRecoveryCode indicates an expected call of VerifyRecoveryCode.
func (mr *MockAuthServiceClientMockRecorder) VerifyRecoveryCode(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRecoveryCode", reflect.TypeOf((*MockAuthServiceClient)(nil).VerifyRecoveryCode), varargs...)
}

// YandexLogin mocks base method.
func (m *MockAuthServiceClient) YandexLogin(arg0 context.Context, arg1 *auth.YandexLoginRequest, arg2 ...grpc.CallOption) (*auth.LoginResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "YandexLogin", varargs...)
	ret0, _ := ret[0].(*auth.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// YandexLogin indicates an expected call of YandexLogin.
func (mr *MockAuthServiceClientMockRecorder) YandexLogin(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "YandexLogin", reflect.TypeOf((*MockAuthServiceClient)(nil).YandexLogin), varargs...)
}
