// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_TheBugs/internal/delivery/grpc/generated/complex (interfaces: ComplexServiceClient)

// Package grpc_client is a generated GoMock package.
package grpc_client

import (
	context "context"
	reflect "reflect"

	complex "github.com/go-park-mail-ru/2026_1_TheBugs/internal/delivery/grpc/generated/complex"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockComplexServiceClient is a mock of ComplexServiceClient interface.
type MockComplexServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockComplexServiceClientMockRecorder
}

// MockComplexServiceClientMockRecorder is the mock recorder for MockComplexServiceClient.
type MockComplexServiceClientMockRecorder struct {
	mock *MockComplexServiceClient
}

// NewMockComplexServiceClient creates a new mock instance.
func NewMockComplexServiceClient(ctrl *gomock.Controller) *MockComplexServiceClient {
	mock := &MockComplexServiceClient{ctrl: ctrl}
	mock.recorder = &MockComplexServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComplexServiceClient) EXPECT() *MockComplexServiceClientMockRecorder {
	return m.recorder
}

// GetAllDevelopers mocks base method.
func (m *MockComplexServiceClient) GetAllDevelopers(arg0 context.Context, arg1 *emptypb.Empty, arg2 ...grpc.CallOption) (*complex.GetAllDevelopersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllDevelopers", varargs...)
	ret0, _ := ret[0].(*complex.GetAllDevelopersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllDevelopers indicates an expected call of GetAllDevelopers.
func (mr *MockComplexServiceClientMockRecorder) GetAllDevelopers(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDevelopers", reflect.TypeOf((*MockComplexServiceClient)(nil).GetAllDevelopers), varargs...)
}

// GetComplex mocks base method.
func (m *MockComplexServiceClient) GetComplex(arg0 context.Context, arg1 *complex.GetComplexRequest, arg2 ...grpc.CallOption) (*complex.GetComplexResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetComplex", varargs...)
	ret0, _ := ret[0].(*complex.GetComplexResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComplex indicates an expected call of GetComplex.
func (mr *MockComplexServiceClientMockRecorder) GetComplex(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComplex", reflect.TypeOf((*MockComplexServiceClient)(nil).GetComplex), varargs...)
}

// GetComplexesByDeveloperID mocks base method.
func (m *MockComplexServiceClient) GetComplexesByDeveloperID(arg0 context.Context, arg1 *complex.GetComplexesByDeveloperIDRequest, arg2 ...grpc.CallOption) (*complex.GetComplexesByDeveloperIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetComplexesByDeveloperID", varargs...)
	ret0, _ := ret[0].(*complex.GetComplexesByDeveloperIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComplexesByDeveloperID indicates an expected call of GetComplexesByDeveloperID.
func (mr *MockComplexServiceClientMockRecorder) GetComplexesByDeveloperID(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComplexesByDeveloperID", reflect.TypeOf((*MockComplexServiceClient)(nil).GetComplexesByDeveloperID), varargs...)
}
