// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_TheBugs/internal/delivery/grpc/generated/poster (interfaces: PosterServiceClient)

// Package grpc_client is a generated GoMock package.
package grpc_client

import (
	context "context"
	reflect "reflect"

	poster "github.com/go-park-mail-ru/2026_1_TheBugs/internal/delivery/grpc/generated/poster"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockPosterServiceClient is a mock of PosterServiceClient interface.
type MockPosterServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockPosterServiceClientMockRecorder
}

// MockPosterServiceClientMockRecorder is the mock recorder for MockPosterServiceClient.
type MockPosterServiceClientMockRecorder struct {
	mock *MockPosterServiceClient
}

// NewMockPosterServiceClient creates a new mock instance.
func NewMockPosterServiceClient(ctrl *gomock.Controller) *MockPosterServiceClient {
	mock := &MockPosterServiceClient{ctrl: ctrl}
	mock.recorder = &MockPosterServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPosterServiceClient) EXPECT() *MockPosterServiceClientMockRecorder {
	return m.recorder
}

// AddFavoritePoster mocks base method.
func (m *MockPosterServiceClient) AddFavoritePoster(arg0 context.Context, arg1 *poster.AddFavoritePosterRequest, arg2 ...grpc.CallOption) (*poster.AddFavoritePosterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddFavoritePoster", varargs...)
	ret0, _ := ret[0].(*poster.AddFavoritePosterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddFavoritePoster indicates an expected call of AddFavoritePoster.
func (mr *MockPosterServiceClientMockRecorder) AddFavoritePoster(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFavoritePoster", reflect.TypeOf((*MockPosterServiceClient)(nil).AddFavoritePoster), varargs...)
}

// AddPosterRoommate mocks base method.
func (m *MockPosterServiceClient) AddPosterRoommate(arg0 context.Context, arg1 *poster.AddPosterRoommateRequest, arg2 ...grpc.CallOption) (*poster.AddPosterRoommateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddPosterRoommate", varargs...)
	ret0, _ := ret[0].(*poster.AddPosterRoommateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPosterRoommate indicates an expected call of AddPosterRoommate.
func (mr *MockPosterServiceClientMockRecorder) AddPosterRoommate(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPosterRoommate", reflect.TypeOf((*MockPosterServiceClient)(nil).AddPosterRoommate), varargs...)
}

// AddViewPoster mocks base method.
func (m *MockPosterServiceClient) AddViewPoster(arg0 context.Context, arg1 *poster.AddViewPosterRequest, arg2 ...grpc.CallOption) (*poster.AddViewPosterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddViewPoster", varargs...)
	ret0, _ := ret[0].(*poster.AddViewPosterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddViewPoster indicates an expected call of AddViewPoster.
func (mr *MockPosterServiceClientMockRecorder) AddViewPoster(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddViewPoster", reflect.TypeOf((*MockPosterServiceClient)(nil).AddViewPoster), varargs...)
}

// CreateFlatPoster mocks base method.
func (m *MockPosterServiceClient) CreateFlatPoster(arg0 context.Context, arg1 ...grpc.CallOption) (grpc.ClientStreamingClient[poster.CreateFlatPosterRequest, poster.CreateFlatPosterResponse], error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateFlatPoster", varargs...)
	ret0, _ := ret[0].(grpc.ClientStreamingClient[poster.CreateFlatPosterRequest, poster.CreateFlatPosterResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFlatPoster indicates an expected call of CreateFlatPoster.
func (mr *MockPosterServiceClientMockRecorder) CreateFlatPoster(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFlatPoster", reflect.TypeOf((*MockPosterServiceClient)(nil).CreateFlatPoster), varargs...)
}

// DeleteFavoritePoster mocks base method.
func (m *MockPosterServiceClient) DeleteFavoritePoster(arg0 context.Context, arg1 *poster.DeleteFavoritePosterRequest, arg2 ...grpc.CallOption) (*poster.DeleteFavoritePosterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteFavoritePoster", varargs...)
	ret0, _ := ret[0].(*poster.DeleteFavoritePosterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFavoritePoster indicates an expected call of DeleteFavoritePoster.
func (mr *MockPosterServiceClientMockRecorder) DeleteFavoritePoster(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFavoritePoster", reflect.TypeOf((*MockPosterServiceClient)(nil).DeleteFavoritePoster), varargs...)
}

// DeleteFlatPoster mocks base method.
func (m *MockPosterServiceClient) DeleteFlatPoster(arg0 context.Context, arg1 *poster.DeleteFlatPosterRequest, arg2 ...grpc.CallOption) (*poster.DeleteFlatPosterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteFlatPoster", varargs...)
	ret0, _ := ret[0].(*poster.DeleteFlatPosterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFlatPoster indicates an expected call of DeleteFlatPoster.
func (mr *MockPosterServiceClientMockRecorder) DeleteFlatPoster(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFlatPoster", reflect.TypeOf((*MockPosterServiceClient)(nil).DeleteFlatPoster), varargs...)
}

// GenerateDescription mocks base method.
func (m *MockPosterServiceClient) GenerateDescription(arg0 context.Context, arg1 *poster.GenerateDescriptionRequest, arg2 ...grpc.CallOption) (*poster.GenerateDescriptionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GenerateDescription", varargs...)
	ret0, _ := ret[0].(*poster.GenerateDescriptionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateDescription indicates an expected call of GenerateDescription.
func (mr *MockPosterServiceClientMockRecorder) GenerateDescription(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDescription", reflect.TypeOf((*MockPosterServiceClient)(nil).GenerateDescription), varargs...)
}

// GetFavoritePosters mocks base method.
func (m *MockPosterServiceClient) GetFavoritePosters(arg0 context.Context, arg1 *poster.GetFavoritePostersRequest, arg2 ...grpc.CallOption) (*poster.GetFavoritePostersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFavoritePosters", varargs...)
	ret0, _ := ret[0].(*poster.GetFavoritePostersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoritePosters indicates an expected call of GetFavoritePosters.
func (mr *MockPosterServiceClientMockRecorder) GetFavoritePosters(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoritePosters", reflect.TypeOf((*MockPosterServiceClient)(nil).GetFavoritePosters), varargs...)
}

// GetFavoritesCountPoster mocks base method.
func (m *MockPosterServiceClient) GetFavoritesCountPoster(arg0 context.Context, arg1 *poster.GetFavoritesCountPosterRequest, arg2 ...grpc.CallOption) (*poster.GetFavoritesCountPosterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFavoritesCountPoster", varargs...)
	ret0, _ := ret[0].(*poster.GetFavoritesCountPosterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoritesCountPoster indicates an expected call of GetFavoritesCountPoster.
func (mr *MockPosterServiceClientMockRecorder) GetFavoritesCountPoster(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoritesCountPoster", reflect.TypeOf((*MockPosterServiceClient)(nil).GetFavoritesCountPoster), varargs...)
}

// GetPosterByAlias mocks base method.
func (m *MockPosterServiceClient) GetPosterByAlias(arg0 context.Context, arg1 *poster.GetPosterByAliasRequest, arg2 ...grpc.CallOption) (*poster.GetPosterByAliasResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPosterByAlias", varargs...)
	ret0, _ := ret[0].(*poster.GetPosterByAliasResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPosterByAlias indicates an expected call of GetPosterByAlias.
func (mr *MockPosterServiceClientMockRecorder) GetPosterByAlias(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPosterByAlias", reflect.TypeOf((*MockPosterServiceClient)(nil).GetPosterByAlias), varargs...)
}

// GetPosterRoommates mocks base method.
func (m *MockPosterServiceClient) GetPosterRoommates(arg0 context.Context, arg1 *poster.GetPosterRoommatesRequest, arg2 ...grpc.CallOption) (*poster.GetPosterRoommatesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPosterRoommates", varargs...)
	ret0, _ := ret[0].(*poster.GetPosterRoommatesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPosterRoommates indicates an expected call of GetPosterRoommates.
func (mr *MockPosterServiceClientMockRecorder) GetPosterRoommates(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPosterRoommates", reflect.TypeOf((*MockPosterServiceClient)(nil).GetPosterRoommates), varargs...)
}

// GetPostersByCoords mocks base method.
func (m *MockPosterServiceClient) GetPostersByCoords(arg0 context.Context, arg1 *poster.GetPostersByCoordsRequest, arg2 ...grpc.CallOption) (*poster.GetPostersByCoordsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPostersByCoords", varargs...)
	ret0, _ := ret[0].(*poster.GetPostersByCoordsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostersByCoords indicates an expected call of GetPostersByCoords.
func (mr *MockPosterServiceClientMockRecorder) GetPostersByCoords(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostersByCoords", reflect.TypeOf((*MockPosterServiceClient)(nil).GetPostersByCoords), varargs...)
}

// GetPostersByRadius mocks base method.
func (m *MockPosterServiceClient) GetPostersByRadius(arg0 context.Context, arg1 *poster.GetPostersByRadiusRequest, arg2 ...grpc.CallOption) (*poster.GetPostersByRadiusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPostersByRadius", varargs...)
	ret0, _ := ret[0].(*poster.GetPostersByRadiusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostersByRadius indicates an expected call of GetPostersByRadius.
func (mr *MockPosterServiceClientMockRecorder) GetPostersByRadius(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostersByRadius", reflect.TypeOf((*MockPosterServiceClient)(nil).GetPostersByRadius), varargs...)
}

// GetPostersByUserID mocks base method.
func (m *MockPosterServiceClient) GetPostersByUserID(arg0 context.Context, arg1 *poster.GetPostersByUserIDRequest, arg2 ...grpc.CallOption) (*poster.GetPostersByUserIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPostersByUserID", varargs...)
	ret0, _ := ret[0].(*poster.GetPostersByUserIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostersByUserID indicates an expected call of GetPostersByUserID.
func (mr *MockPosterServiceClientMockRecorder) GetPostersByUserID(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostersByUserID", reflect.TypeOf((*MockPosterServiceClient)(nil).GetPostersByUserID), varargs...)
}

// GetPriceHistoryPoster mocks base method.
func (m *MockPosterServiceClient) GetPriceHistoryPoster(arg0 context.Context, arg1 *poster.GetPriceHistoryPosterRequest, arg2 ...grpc.CallOption) (*poster.GetPriceHistoryPosterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPriceHistoryPoster", varargs...)
	ret0, _ := ret[0].(*poster.GetPriceHistoryPosterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceHistoryPoster indicates an expected call of GetPriceHistoryPoster.
func (mr *MockPosterServiceClientMockRecorder) GetPriceHistoryPoster(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceHistoryPoster", reflect.TypeOf((*MockPosterServiceClient)(nil).GetPriceHistoryPoster), varargs...)
}

// GetViewsPoster mocks base method.
func (m *MockPosterServiceClient) GetViewsPoster(arg0 context.Context, arg1 *poster.GetViewsPosterRequest, arg2 ...grpc.CallOption) (*poster.GetViewsPosterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetViewsPoster", varargs...)
	ret0, _ := ret[0].(*poster.GetViewsPosterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetViewsPoster indicates an expected call of GetViewsPoster.
func (mr *MockPosterServiceClientMockRecorder) GetViewsPoster(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetViewsPoster", reflect.TypeOf((*MockPosterServiceClient)(nil).GetViewsPoster), varargs...)
}

// SearchPosters mocks base method.
func (m *MockPosterServiceClient) SearchPosters(arg0 context.Context, arg1 *poster.SearchPostersRequest, arg2 ...grpc.CallOption) (*poster.SearchPostersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchPosters", varargs...)
	ret0, _ := ret[0].(*poster.SearchPostersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPosters indicates an expected call of SearchPosters.
func (mr *MockPosterServiceClientMockRecorder) SearchPosters(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPosters", reflect.TypeOf((*MockPosterServiceClient)(nil).SearchPosters), varargs...)
}

// UpdateFlatPoster mocks base method.
func (m *MockPosterServiceClient) UpdateFlatPoster(arg0 context.Context, arg1 ...grpc.CallOption) (grpc.ClientStreamingClient[poster.UpdateFlatPosterRequest, poster.UpdateFlatPosterResponse], error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateFlatPoster", varargs...)
	ret0, _ := ret[0].(grpc.ClientStreamingClient[poster.UpdateFlatPosterRequest, poster.UpdateFlatPosterResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFlatPoster indicates an expected call of UpdateFlatPoster.
func (mr *MockPosterServiceClientMockRecorder) UpdateFlatPoster(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFlatPoster", reflect.TypeOf((*MockPosterServiceClient)(nil).UpdateFlatPoster), varargs...)
}
