// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package response

import (
	json "encoding/json"
	dto "github.com/go-park-mail-ru/2026_1_TheBugs/internal/usecase/dto"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4b608a57DecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse(in *jlexer.Lexer, out *DevelopersResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "len":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Len = int(in.Int())
			}
		case "developers":
			if in.IsNull() {
				in.Skip()
				out.Developers = nil
			} else {
				in.Delim('[')
				if out.Developers == nil {
					if !in.IsDelim(']') {
						out.Developers = make([]dto.DeveloperDTO, 0, 2)
					} else {
						out.Developers = []dto.DeveloperDTO{}
					}
				} else {
					out.Developers = (out.Developers)[:0]
				}
				for !in.IsDelim(']') {
					var v1 dto.DeveloperDTO
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Developers = append(out.Developers, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4b608a57EncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse(out *jwriter.Writer, in DevelopersResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"len\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Len))
	}
	{
		const prefix string = ",\"developers\":"
		out.RawString(prefix)
		if in.Developers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Developers {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DevelopersResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4b608a57EncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DevelopersResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4b608a57EncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DevelopersResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4b608a57DecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DevelopersResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4b608a57DecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse(l, v)
}
func easyjson4b608a57DecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse1(in *jlexer.Lexer, out *CompaniesResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "len":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Len = int(in.Int())
			}
		case "utility_companies":
			if in.IsNull() {
				in.Skip()
				out.Companies = nil
			} else {
				in.Delim('[')
				if out.Companies == nil {
					if !in.IsDelim(']') {
						out.Companies = make([]dto.UtilityCompanyCardDTO, 0, 1)
					} else {
						out.Companies = []dto.UtilityCompanyCardDTO{}
					}
				} else {
					out.Companies = (out.Companies)[:0]
				}
				for !in.IsDelim(']') {
					var v4 dto.UtilityCompanyCardDTO
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					out.Companies = append(out.Companies, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4b608a57EncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse1(out *jwriter.Writer, in CompaniesResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"len\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Len))
	}
	{
		const prefix string = ",\"utility_companies\":"
		out.RawString(prefix)
		if in.Companies == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Companies {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CompaniesResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4b608a57EncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CompaniesResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4b608a57EncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CompaniesResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4b608a57DecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CompaniesResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4b608a57DecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse1(l, v)
}
