// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package response

import (
	json "encoding/json"
	dto "github.com/go-park-mail-ru/2026_1_TheBugs/internal/usecase/dto"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse(in *jlexer.Lexer, out *PriceHistoryResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "history":
			if in.IsNull() {
				in.Skip()
				out.History = nil
			} else {
				in.Delim('[')
				if out.History == nil {
					if !in.IsDelim(']') {
						out.History = make([]dto.PriceHistoryDTO, 0, 2)
					} else {
						out.History = []dto.PriceHistoryDTO{}
					}
				} else {
					out.History = (out.History)[:0]
				}
				for !in.IsDelim(']') {
					var v1 dto.PriceHistoryDTO
					easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(in, &v1)
					out.History = append(out.History, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "count":
			out.Count = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse(out *jwriter.Writer, in PriceHistoryResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"history\":"
		out.RawString(prefix[1:])
		if in.History == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.History {
				if v2 > 0 {
					out.RawByte(',')
				}
				easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(out, v3)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"count\":"
		out.RawString(prefix)
		out.Int(int(in.Count))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PriceHistoryResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PriceHistoryResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PriceHistoryResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PriceHistoryResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse(l, v)
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(in *jlexer.Lexer, out *dto.PriceHistoryDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "date":
			out.Date = string(in.String())
		case "price":
			out.Price = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(out *jwriter.Writer, in dto.PriceHistoryDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"date\":"
		out.RawString(prefix[1:])
		out.String(string(in.Date))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	out.RawByte('}')
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse1(in *jlexer.Lexer, out *PosterViewsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "views":
			out.Views = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse1(out *jwriter.Writer, in PosterViewsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"views\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Views))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PosterViewsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PosterViewsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PosterViewsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PosterViewsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse1(l, v)
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse2(in *jlexer.Lexer, out *PosterResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "poster":
			if in.IsNull() {
				in.Skip()
				out.Poster = nil
			} else {
				if out.Poster == nil {
					out.Poster = new(dto.PosterDTO)
				}
				easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(in, out.Poster)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse2(out *jwriter.Writer, in PosterResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"poster\":"
		out.RawString(prefix[1:])
		if in.Poster == nil {
			out.RawString("null")
		} else {
			easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(out, *in.Poster)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PosterResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PosterResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PosterResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PosterResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse2(l, v)
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(in *jlexer.Lexer, out *dto.PosterDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "alias":
			out.Alias = string(in.String())
		case "price":
			out.Price = float64(in.Float64())
		case "category":
			easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(in, &out.Category)
		case "description":
			out.Description = string(in.String())
		case "area":
			out.Area = float64(in.Float64())
		case "building_geo":
			easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(in, &out.Geo)
		case "address":
			out.Address = string(in.String())
		case "district":
			if in.IsNull() {
				in.Skip()
				out.District = nil
			} else {
				if out.District == nil {
					out.District = new(string)
				}
				*out.District = string(in.String())
			}
		case "metro":
			if in.IsNull() {
				in.Skip()
				out.Metro = nil
			} else {
				if out.Metro == nil {
					out.Metro = new(string)
				}
				*out.Metro = string(in.String())
			}
		case "metro_geo":
			if in.IsNull() {
				in.Skip()
				out.MetroGeo = nil
			} else {
				if out.MetroGeo == nil {
					out.MetroGeo = new(dto.GeographyDTO)
				}
				easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(in, out.MetroGeo)
			}
		case "city":
			out.City = string(in.String())
		case "floor_count":
			out.FloorCount = int(in.Int())
		case "images":
			if in.IsNull() {
				in.Skip()
				out.Images = nil
			} else {
				in.Delim('[')
				if out.Images == nil {
					if !in.IsDelim(']') {
						out.Images = make([]dto.PhotoDTO, 0, 2)
					} else {
						out.Images = []dto.PhotoDTO{}
					}
				} else {
					out.Images = (out.Images)[:0]
				}
				for !in.IsDelim(']') {
					var v4 dto.PhotoDTO
					easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto4(in, &v4)
					out.Images = append(out.Images, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "seller":
			easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto5(in, &out.Seller)
		case "flat":
			if in.IsNull() {
				in.Skip()
				out.Flat = nil
			} else {
				if out.Flat == nil {
					out.Flat = new(dto.FlatDTO)
				}
				easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto6(in, out.Flat)
			}
		case "house":
			if in.IsNull() {
				in.Skip()
				out.House = nil
			} else {
				if out.House == nil {
					out.House = new(dto.HouseDTO)
				}
				easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto7(in, out.House)
			}
		case "facilities":
			if in.IsNull() {
				in.Skip()
				out.Facilities = nil
			} else {
				in.Delim('[')
				if out.Facilities == nil {
					if !in.IsDelim(']') {
						out.Facilities = make([]dto.FacilityDTO, 0, 2)
					} else {
						out.Facilities = []dto.FacilityDTO{}
					}
				} else {
					out.Facilities = (out.Facilities)[:0]
				}
				for !in.IsDelim(']') {
					var v5 dto.FacilityDTO
					easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto8(in, &v5)
					out.Facilities = append(out.Facilities, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "company":
			if in.IsNull() {
				in.Skip()
				out.Company = nil
			} else {
				if out.Company == nil {
					out.Company = new(dto.UtilityCompanyCardDTO)
				}
				easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto9(in, out.Company)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(out *jwriter.Writer, in dto.PosterDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix)
		out.String(string(in.Alias))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(out, in.Category)
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"area\":"
		out.RawString(prefix)
		out.Float64(float64(in.Area))
	}
	{
		const prefix string = ",\"building_geo\":"
		out.RawString(prefix)
		easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(out, in.Geo)
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"district\":"
		out.RawString(prefix)
		if in.District == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.District))
		}
	}
	{
		const prefix string = ",\"metro\":"
		out.RawString(prefix)
		if in.Metro == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Metro))
		}
	}
	{
		const prefix string = ",\"metro_geo\":"
		out.RawString(prefix)
		if in.MetroGeo == nil {
			out.RawString("null")
		} else {
			easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(out, *in.MetroGeo)
		}
	}
	{
		const prefix string = ",\"city\":"
		out.RawString(prefix)
		out.String(string(in.City))
	}
	{
		const prefix string = ",\"floor_count\":"
		out.RawString(prefix)
		out.Int(int(in.FloorCount))
	}
	{
		const prefix string = ",\"images\":"
		out.RawString(prefix)
		if in.Images == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v6, v7 := range in.Images {
				if v6 > 0 {
					out.RawByte(',')
				}
				easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto4(out, v7)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"seller\":"
		out.RawString(prefix)
		easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto5(out, in.Seller)
	}
	if in.Flat != nil {
		const prefix string = ",\"flat\":"
		out.RawString(prefix)
		easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto6(out, *in.Flat)
	}
	if in.House != nil {
		const prefix string = ",\"house\":"
		out.RawString(prefix)
		easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto7(out, *in.House)
	}
	{
		const prefix string = ",\"facilities\":"
		out.RawString(prefix)
		if in.Facilities == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Facilities {
				if v8 > 0 {
					out.RawByte(',')
				}
				easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto8(out, v9)
			}
			out.RawByte(']')
		}
	}
	if in.Company != nil {
		const prefix string = ",\"company\":"
		out.RawString(prefix)
		easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto9(out, *in.Company)
	}
	out.RawByte('}')
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto9(in *jlexer.Lexer, out *dto.UtilityCompanyCardDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "company_name":
			out.CompanyName = string(in.String())
		case "avatar_url":
			if in.IsNull() {
				in.Skip()
				out.AvatarURL = nil
			} else {
				if out.AvatarURL == nil {
					out.AvatarURL = new(string)
				}
				*out.AvatarURL = string(in.String())
			}
		case "alias":
			out.Alias = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto9(out *jwriter.Writer, in dto.UtilityCompanyCardDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"company_name\":"
		out.RawString(prefix)
		out.String(string(in.CompanyName))
	}
	{
		const prefix string = ",\"avatar_url\":"
		out.RawString(prefix)
		if in.AvatarURL == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.AvatarURL))
		}
	}
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix)
		out.String(string(in.Alias))
	}
	out.RawByte('}')
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto8(in *jlexer.Lexer, out *dto.FacilityDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "alias":
			out.Alias = string(in.String())
		case "name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto8(out *jwriter.Writer, in dto.FacilityDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix[1:])
		out.String(string(in.Alias))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto7(in *jlexer.Lexer, out *dto.HouseDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto7(out *jwriter.Writer, in dto.HouseDTO) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto6(in *jlexer.Lexer, out *dto.FlatDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "flat_category":
			out.FlatCategory = string(in.String())
		case "flat_number":
			out.Number = int(in.Int())
		case "floor":
			out.Floor = int(in.Int())
		case "room_count":
			out.RoomCount = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto6(out *jwriter.Writer, in dto.FlatDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"flat_category\":"
		out.RawString(prefix[1:])
		out.String(string(in.FlatCategory))
	}
	{
		const prefix string = ",\"flat_number\":"
		out.RawString(prefix)
		out.Int(int(in.Number))
	}
	{
		const prefix string = ",\"floor\":"
		out.RawString(prefix)
		out.Int(int(in.Floor))
	}
	{
		const prefix string = ",\"room_count\":"
		out.RawString(prefix)
		out.Int(int(in.RoomCount))
	}
	out.RawByte('}')
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto5(in *jlexer.Lexer, out *dto.PosterSellerDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "first_name":
			out.SellerFirstName = string(in.String())
		case "last_name":
			out.SellerLastName = string(in.String())
		case "phone":
			out.SellerPhone = string(in.String())
		case "avatar_url":
			if in.IsNull() {
				in.Skip()
				out.SellerAvatarURL = nil
			} else {
				if out.SellerAvatarURL == nil {
					out.SellerAvatarURL = new(string)
				}
				*out.SellerAvatarURL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto5(out *jwriter.Writer, in dto.PosterSellerDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"first_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.SellerFirstName))
	}
	{
		const prefix string = ",\"last_name\":"
		out.RawString(prefix)
		out.String(string(in.SellerLastName))
	}
	{
		const prefix string = ",\"phone\":"
		out.RawString(prefix)
		out.String(string(in.SellerPhone))
	}
	{
		const prefix string = ",\"avatar_url\":"
		out.RawString(prefix)
		if in.SellerAvatarURL == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.SellerAvatarURL))
		}
	}
	out.RawByte('}')
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto4(in *jlexer.Lexer, out *dto.PhotoDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "img_url":
			out.ImgURL = string(in.String())
		case "order":
			out.Order = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto4(out *jwriter.Writer, in dto.PhotoDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"img_url\":"
		out.RawString(prefix[1:])
		out.String(string(in.ImgURL))
	}
	{
		const prefix string = ",\"order\":"
		out.RawString(prefix)
		out.Int(int(in.Order))
	}
	out.RawByte('}')
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(in *jlexer.Lexer, out *dto.GeographyDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "lat":
			out.Lat = float64(in.Float64())
		case "lon":
			out.Lon = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(out *jwriter.Writer, in dto.GeographyDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"lat\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.Lat))
	}
	{
		const prefix string = ",\"lon\":"
		out.RawString(prefix)
		out.Float64(float64(in.Lon))
	}
	out.RawByte('}')
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(in *jlexer.Lexer, out *dto.CategoryDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "alias":
			out.Alias = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(out *jwriter.Writer, in dto.CategoryDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix)
		out.String(string(in.Alias))
	}
	out.RawByte('}')
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse3(in *jlexer.Lexer, out *PosterFavoritesCountResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "favorites":
			out.Count = int(in.Int())
		case "is_favorite":
			out.IsFavorite = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse3(out *jwriter.Writer, in PosterFavoritesCountResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"favorites\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Count))
	}
	{
		const prefix string = ",\"is_favorite\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsFavorite))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PosterFavoritesCountResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PosterFavoritesCountResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PosterFavoritesCountResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PosterFavoritesCountResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse3(l, v)
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse4(in *jlexer.Lexer, out *MyPostersResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "len":
			out.Len = int(in.Int())
		case "posters":
			if in.IsNull() {
				in.Skip()
				out.Posters = nil
			} else {
				in.Delim('[')
				if out.Posters == nil {
					if !in.IsDelim(']') {
						out.Posters = make([]dto.MyPosterDTO, 0, 0)
					} else {
						out.Posters = []dto.MyPosterDTO{}
					}
				} else {
					out.Posters = (out.Posters)[:0]
				}
				for !in.IsDelim(']') {
					var v10 dto.MyPosterDTO
					easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto10(in, &v10)
					out.Posters = append(out.Posters, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse4(out *jwriter.Writer, in MyPostersResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"len\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Len))
	}
	{
		const prefix string = ",\"posters\":"
		out.RawString(prefix)
		if in.Posters == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.Posters {
				if v11 > 0 {
					out.RawByte(',')
				}
				easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto10(out, v12)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MyPostersResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MyPostersResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MyPostersResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MyPostersResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse4(l, v)
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto10(in *jlexer.Lexer, out *dto.MyPosterDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "alias":
			out.Alias = string(in.String())
		case "address":
			out.Address = string(in.String())
		case "area":
			out.Area = float64(in.Float64())
		case "price":
			out.Price = float64(in.Float64())
		case "avatar_url":
			if in.IsNull() {
				in.Skip()
				out.AvatarURl = nil
			} else {
				if out.AvatarURl == nil {
					out.AvatarURl = new(string)
				}
				*out.AvatarURl = string(in.String())
			}
		case "category":
			easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(in, &out.Category)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto10(out *jwriter.Writer, in dto.MyPosterDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix)
		out.String(string(in.Alias))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"area\":"
		out.RawString(prefix)
		out.Float64(float64(in.Area))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"avatar_url\":"
		out.RawString(prefix)
		if in.AvatarURl == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.AvatarURl))
		}
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(out, in.Category)
	}
	out.RawByte('}')
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse5(in *jlexer.Lexer, out *MetroResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "len":
			out.Len = int(in.Int())
		case "metro_stations":
			if in.IsNull() {
				in.Skip()
				out.MetroStations = nil
			} else {
				in.Delim('[')
				if out.MetroStations == nil {
					if !in.IsDelim(']') {
						out.MetroStations = make([]dto.MetroStationDTO, 0, 2)
					} else {
						out.MetroStations = []dto.MetroStationDTO{}
					}
				} else {
					out.MetroStations = (out.MetroStations)[:0]
				}
				for !in.IsDelim(']') {
					var v13 dto.MetroStationDTO
					easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto11(in, &v13)
					out.MetroStations = append(out.MetroStations, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse5(out *jwriter.Writer, in MetroResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"len\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Len))
	}
	{
		const prefix string = ",\"metro_stations\":"
		out.RawString(prefix)
		if in.MetroStations == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.MetroStations {
				if v14 > 0 {
					out.RawByte(',')
				}
				easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto11(out, v15)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MetroResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MetroResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MetroResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MetroResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse5(l, v)
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto11(in *jlexer.Lexer, out *dto.MetroStationDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "station_name":
			out.StationName = string(in.String())
		case "station_geo":
			easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(in, &out.StationGeo)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto11(out *jwriter.Writer, in dto.MetroStationDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"station_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.StationName))
	}
	{
		const prefix string = ",\"station_geo\":"
		out.RawString(prefix)
		easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(out, in.StationGeo)
	}
	out.RawByte('}')
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse6(in *jlexer.Lexer, out *GenerateDescriptionResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "description":
			out.Description = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse6(out *jwriter.Writer, in GenerateDescriptionResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix[1:])
		out.String(string(in.Description))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GenerateDescriptionResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GenerateDescriptionResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GenerateDescriptionResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GenerateDescriptionResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse6(l, v)
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse7(in *jlexer.Lexer, out *CreatedPosterResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "poster":
			if in.IsNull() {
				in.Skip()
				out.Poster = nil
			} else {
				if out.Poster == nil {
					out.Poster = new(dto.CreatedPoster)
				}
				easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto12(in, out.Poster)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse7(out *jwriter.Writer, in CreatedPosterResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"poster\":"
		out.RawString(prefix[1:])
		if in.Poster == nil {
			out.RawString("null")
		} else {
			easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto12(out, *in.Poster)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreatedPosterResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreatedPosterResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreatedPosterResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreatedPosterResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiResponse7(l, v)
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto12(in *jlexer.Lexer, out *dto.CreatedPoster) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "alias":
			out.Alias = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto12(out *jwriter.Writer, in dto.CreatedPoster) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix)
		out.String(string(in.Alias))
	}
	out.RawByte('}')
}
