run:
  allow-parallel-runners: true
  go: '1.23'
  skip-dirs:
    - vendor
    - testdata
    
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - gosimple
    - ineffassign

issues:
  exclude-use-default: false