services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres
    environment:
      POSTGRES_USER: thebugs
      POSTGRES_PASSWORD: thebugs
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thebugs -d main"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    environment:
    - TZ=Europe/Moscow
    - MAILDEV_WEB_PORT=1080
    - MAILDEV_SMTP_PORT=1025
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"