// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package auth

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson888c126aDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiAuth(in *jlexer.Lexer, out *LoginResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "access_token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccessToken = string(in.String())
			}
		case "expire_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccessTokenExp = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson888c126aEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiAuth(out *jwriter.Writer, in LoginResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"access_token\":"
		out.RawString(prefix[1:])
		out.String(string(in.AccessToken))
	}
	{
		const prefix string = ",\"expire_at\":"
		out.RawString(prefix)
		out.Int(int(in.AccessTokenExp))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LoginResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson888c126aEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiAuth(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LoginResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson888c126aEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiAuth(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LoginResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson888c126aDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiAuth(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LoginResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson888c126aDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiAuth(l, v)
}
func easyjson888c126aDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiAuth1(in *jlexer.Lexer, out *FormDataCredential) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Email = string(in.String())
			}
		case "Password":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Password = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson888c126aEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiAuth1(out *jwriter.Writer, in FormDataCredential) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Email\":"
		out.RawString(prefix[1:])
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"Password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FormDataCredential) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson888c126aEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiAuth1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FormDataCredential) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson888c126aEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiAuth1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FormDataCredential) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson888c126aDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiAuth1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FormDataCredential) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson888c126aDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiAuth1(l, v)
}
func easyjson888c126aDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiAuth2(in *jlexer.Lexer, out *FormDataCreateUser) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Email = string(in.String())
			}
		case "Password":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Password = string(in.String())
			}
		case "Phone":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Phone = string(in.String())
			}
		case "FirstName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FirstName = string(in.String())
			}
		case "LastName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastName = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson888c126aEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiAuth2(out *jwriter.Writer, in FormDataCreateUser) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Email\":"
		out.RawString(prefix[1:])
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"Password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	{
		const prefix string = ",\"Phone\":"
		out.RawString(prefix)
		out.String(string(in.Phone))
	}
	{
		const prefix string = ",\"FirstName\":"
		out.RawString(prefix)
		out.String(string(in.FirstName))
	}
	{
		const prefix string = ",\"LastName\":"
		out.RawString(prefix)
		out.String(string(in.LastName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FormDataCreateUser) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson888c126aEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiAuth2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FormDataCreateUser) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson888c126aEncodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiAuth2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FormDataCreateUser) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson888c126aDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiAuth2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FormDataCreateUser) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson888c126aDecodeGithubComGoParkMailRu20261TheBugsInternalDeliveryRestapiAuth2(l, v)
}
