// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson86c2dad6DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(in *jlexer.Lexer, out *UtilityCompanyDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "phone":
			out.Phone = string(in.String())
		case "company_name":
			out.CompanyName = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "geo":
			easyjson86c2dad6DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(in, &out.GEO)
		case "address":
			out.Address = string(in.String())
		case "avatar_url":
			if in.IsNull() {
				in.Skip()
				out.AvatarURL = nil
			} else {
				if out.AvatarURL == nil {
					out.AvatarURL = new(string)
				}
				*out.AvatarURL = string(in.String())
			}
		case "alias":
			out.Alias = string(in.String())
		case "photos":
			if in.IsNull() {
				in.Skip()
				out.Photos = nil
			} else {
				in.Delim('[')
				if out.Photos == nil {
					if !in.IsDelim(']') {
						out.Photos = make([]PhotoDTO, 0, 2)
					} else {
						out.Photos = []PhotoDTO{}
					}
				} else {
					out.Photos = (out.Photos)[:0]
				}
				for !in.IsDelim(']') {
					var v1 PhotoDTO
					easyjson86c2dad6DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(in, &v1)
					out.Photos = append(out.Photos, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "developer":
			(out.Developer).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson86c2dad6EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(out *jwriter.Writer, in UtilityCompanyDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"phone\":"
		out.RawString(prefix)
		out.String(string(in.Phone))
	}
	{
		const prefix string = ",\"company_name\":"
		out.RawString(prefix)
		out.String(string(in.CompanyName))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"geo\":"
		out.RawString(prefix)
		easyjson86c2dad6EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(out, in.GEO)
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"avatar_url\":"
		out.RawString(prefix)
		if in.AvatarURL == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.AvatarURL))
		}
	}
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix)
		out.String(string(in.Alias))
	}
	{
		const prefix string = ",\"photos\":"
		out.RawString(prefix)
		if in.Photos == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Photos {
				if v2 > 0 {
					out.RawByte(',')
				}
				easyjson86c2dad6EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(out, v3)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"developer\":"
		out.RawString(prefix)
		(in.Developer).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UtilityCompanyDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson86c2dad6EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UtilityCompanyDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson86c2dad6EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UtilityCompanyDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson86c2dad6DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UtilityCompanyDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson86c2dad6DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(l, v)
}
func easyjson86c2dad6DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(in *jlexer.Lexer, out *PhotoDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "img_url":
			out.ImgURL = string(in.String())
		case "order":
			out.Order = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson86c2dad6EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(out *jwriter.Writer, in PhotoDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"img_url\":"
		out.RawString(prefix[1:])
		out.String(string(in.ImgURL))
	}
	{
		const prefix string = ",\"order\":"
		out.RawString(prefix)
		out.Int(int(in.Order))
	}
	out.RawByte('}')
}
func easyjson86c2dad6DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(in *jlexer.Lexer, out *GeographyDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "lat":
			out.Lat = float64(in.Float64())
		case "lon":
			out.Lon = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson86c2dad6EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(out *jwriter.Writer, in GeographyDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"lat\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.Lat))
	}
	{
		const prefix string = ",\"lon\":"
		out.RawString(prefix)
		out.Float64(float64(in.Lon))
	}
	out.RawByte('}')
}
func easyjson86c2dad6DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(in *jlexer.Lexer, out *UtilityCompanyCardDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "company_name":
			out.CompanyName = string(in.String())
		case "avatar_url":
			if in.IsNull() {
				in.Skip()
				out.AvatarURL = nil
			} else {
				if out.AvatarURL == nil {
					out.AvatarURL = new(string)
				}
				*out.AvatarURL = string(in.String())
			}
		case "alias":
			out.Alias = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson86c2dad6EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(out *jwriter.Writer, in UtilityCompanyCardDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"company_name\":"
		out.RawString(prefix)
		out.String(string(in.CompanyName))
	}
	{
		const prefix string = ",\"avatar_url\":"
		out.RawString(prefix)
		if in.AvatarURL == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.AvatarURL))
		}
	}
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix)
		out.String(string(in.Alias))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UtilityCompanyCardDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson86c2dad6EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UtilityCompanyCardDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson86c2dad6EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UtilityCompanyCardDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson86c2dad6DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UtilityCompanyCardDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson86c2dad6DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(l, v)
}
func easyjson86c2dad6DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto4(in *jlexer.Lexer, out *DeveloperDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "developer_id":
			out.DeveloperID = int(in.Int())
		case "developer_name":
			out.DeveloperName = string(in.String())
		case "avatar_url":
			if in.IsNull() {
				in.Skip()
				out.AvatarURL = nil
			} else {
				if out.AvatarURL == nil {
					out.AvatarURL = new(string)
				}
				*out.AvatarURL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson86c2dad6EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto4(out *jwriter.Writer, in DeveloperDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"developer_id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.DeveloperID))
	}
	{
		const prefix string = ",\"developer_name\":"
		out.RawString(prefix)
		out.String(string(in.DeveloperName))
	}
	{
		const prefix string = ",\"avatar_url\":"
		out.RawString(prefix)
		if in.AvatarURL == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.AvatarURL))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DeveloperDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson86c2dad6EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DeveloperDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson86c2dad6EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DeveloperDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson86c2dad6DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DeveloperDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson86c2dad6DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto4(l, v)
}
