// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6c563c13DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(in *jlexer.Lexer, out *FacilityDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "alias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alias = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6c563c13EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(out *jwriter.Writer, in FacilityDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix[1:])
		out.String(string(in.Alias))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FacilityDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6c563c13EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FacilityDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6c563c13EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FacilityDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6c563c13DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FacilityDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6c563c13DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(l, v)
}
