// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  dto

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( FileInput ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* FileInput ) UnmarshalJSON([]byte) error { return nil }
func ( FileInput ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* FileInput ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_FileInput *FileInput
