// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB2fb3a99DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(in *jlexer.Lexer, out *FlatInputDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "FlatCategoryID":
			out.FlatCategoryID = int(in.Int())
		case "Number":
			if in.IsNull() {
				in.Skip()
				out.Number = nil
			} else {
				if out.Number == nil {
					out.Number = new(int)
				}
				*out.Number = int(in.Int())
			}
		case "Floor":
			out.Floor = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB2fb3a99EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(out *jwriter.Writer, in FlatInputDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"FlatCategoryID\":"
		out.RawString(prefix[1:])
		out.Int(int(in.FlatCategoryID))
	}
	{
		const prefix string = ",\"Number\":"
		out.RawString(prefix)
		if in.Number == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.Number))
		}
	}
	{
		const prefix string = ",\"Floor\":"
		out.RawString(prefix)
		out.Int(int(in.Floor))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FlatInputDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB2fb3a99EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FlatInputDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB2fb3a99EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FlatInputDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB2fb3a99DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FlatInputDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB2fb3a99DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(l, v)
}
func easyjsonB2fb3a99DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(in *jlexer.Lexer, out *FlatInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "PropertyID":
			out.PropertyID = int(in.Int())
		case "CategoryID":
			out.CategoryID = int(in.Int())
		case "Floor":
			out.Floor = int(in.Int())
		case "Number":
			if in.IsNull() {
				in.Skip()
				out.Number = nil
			} else {
				if out.Number == nil {
					out.Number = new(int)
				}
				*out.Number = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB2fb3a99EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(out *jwriter.Writer, in FlatInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"PropertyID\":"
		out.RawString(prefix[1:])
		out.Int(int(in.PropertyID))
	}
	{
		const prefix string = ",\"CategoryID\":"
		out.RawString(prefix)
		out.Int(int(in.CategoryID))
	}
	{
		const prefix string = ",\"Floor\":"
		out.RawString(prefix)
		out.Int(int(in.Floor))
	}
	{
		const prefix string = ",\"Number\":"
		out.RawString(prefix)
		if in.Number == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.Number))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FlatInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB2fb3a99EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FlatInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB2fb3a99EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FlatInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB2fb3a99DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FlatInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB2fb3a99DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(l, v)
}
func easyjsonB2fb3a99DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(in *jlexer.Lexer, out *FlatDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "flat_category":
			out.FlatCategory = string(in.String())
		case "flat_number":
			out.Number = int(in.Int())
		case "floor":
			out.Floor = int(in.Int())
		case "room_count":
			out.RoomCount = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB2fb3a99EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(out *jwriter.Writer, in FlatDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"flat_category\":"
		out.RawString(prefix[1:])
		out.String(string(in.FlatCategory))
	}
	{
		const prefix string = ",\"flat_number\":"
		out.RawString(prefix)
		out.Int(int(in.Number))
	}
	{
		const prefix string = ",\"floor\":"
		out.RawString(prefix)
		out.Int(int(in.Floor))
	}
	{
		const prefix string = ",\"room_count\":"
		out.RawString(prefix)
		out.Int(int(in.RoomCount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FlatDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB2fb3a99EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FlatDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB2fb3a99EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FlatDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB2fb3a99DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FlatDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB2fb3a99DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(l, v)
}
