// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA0535929DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(in *jlexer.Lexer, out *MapBounds) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "bbox":
			(out.BBox).UnmarshalEasyJSON(in)
		case "zoom":
			out.Zoom = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA0535929EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(out *jwriter.Writer, in MapBounds) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"bbox\":"
		out.RawString(prefix[1:])
		(in.BBox).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"zoom\":"
		out.RawString(prefix)
		out.Int(int(in.Zoom))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MapBounds) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA0535929EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MapBounds) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA0535929EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MapBounds) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA0535929DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MapBounds) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA0535929DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(l, v)
}
func easyjsonA0535929DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(in *jlexer.Lexer, out *GeographyDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "lat":
			out.Lat = float64(in.Float64())
		case "lon":
			out.Lon = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA0535929EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(out *jwriter.Writer, in GeographyDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"lat\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.Lat))
	}
	{
		const prefix string = ",\"lon\":"
		out.RawString(prefix)
		out.Float64(float64(in.Lon))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GeographyDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA0535929EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GeographyDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA0535929EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GeographyDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA0535929DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GeographyDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA0535929DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(l, v)
}
func easyjsonA0535929DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(in *jlexer.Lexer, out *BBox) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "southWest":
			(out.SouthWest).UnmarshalEasyJSON(in)
		case "northEast":
			(out.NorthEast).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA0535929EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(out *jwriter.Writer, in BBox) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"southWest\":"
		out.RawString(prefix[1:])
		(in.SouthWest).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"northEast\":"
		out.RawString(prefix)
		(in.NorthEast).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BBox) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA0535929EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BBox) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA0535929EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BBox) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA0535929DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BBox) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA0535929DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(l, v)
}
