// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonEbb34541DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(in *jlexer.Lexer, out *MetroStationDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "station_name":
			out.StationName = string(in.String())
		case "station_geo":
			(out.StationGeo).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEbb34541EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(out *jwriter.Writer, in MetroStationDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"station_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.StationName))
	}
	{
		const prefix string = ",\"station_geo\":"
		out.RawString(prefix)
		(in.StationGeo).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MetroStationDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEbb34541EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MetroStationDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEbb34541EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MetroStationDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEbb34541DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MetroStationDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEbb34541DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(l, v)
}
