// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC4d5a6bfDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(in *jlexer.Lexer, out *OAuthCodeFlow) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "code":
			out.Code = string(in.String())
		case "device_id":
			if in.IsNull() {
				in.Skip()
				out.DeviceID = nil
			} else {
				if out.DeviceID == nil {
					out.DeviceID = new(string)
				}
				*out.DeviceID = string(in.String())
			}
		case "state":
			if in.IsNull() {
				in.Skip()
				out.State = nil
			} else {
				if out.State == nil {
					out.State = new(string)
				}
				*out.State = string(in.String())
			}
		case "code_verifier":
			if in.IsNull() {
				in.Skip()
				out.CodeVerifier = nil
			} else {
				if out.CodeVerifier == nil {
					out.CodeVerifier = new(string)
				}
				*out.CodeVerifier = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC4d5a6bfEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(out *jwriter.Writer, in OAuthCodeFlow) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"device_id\":"
		out.RawString(prefix)
		if in.DeviceID == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.DeviceID))
		}
	}
	{
		const prefix string = ",\"state\":"
		out.RawString(prefix)
		if in.State == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.State))
		}
	}
	{
		const prefix string = ",\"code_verifier\":"
		out.RawString(prefix)
		if in.CodeVerifier == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.CodeVerifier))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OAuthCodeFlow) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC4d5a6bfEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OAuthCodeFlow) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC4d5a6bfEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OAuthCodeFlow) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC4d5a6bfDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OAuthCodeFlow) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC4d5a6bfDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(l, v)
}
