// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson49c0357aDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(in *jlexer.Lexer, out *PhotoInputDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "FileHeader":
			if in.IsNull() {
				in.Skip()
				out.FileHeader = nil
			} else {
				if out.FileHeader == nil {
					out.FileHeader = new(FileInput)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.FileHeader).UnmarshalEasyJSON(in)
				}
			}
		case "Order":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Order = int(in.Int())
			}
		case "URL":
			if in.IsNull() {
				in.Skip()
				out.URL = nil
			} else {
				if out.URL == nil {
					out.URL = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.URL = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson49c0357aEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(out *jwriter.Writer, in PhotoInputDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"FileHeader\":"
		out.RawString(prefix[1:])
		if in.FileHeader == nil {
			out.RawString("null")
		} else {
			(*in.FileHeader).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"Order\":"
		out.RawString(prefix)
		out.Int(int(in.Order))
	}
	{
		const prefix string = ",\"URL\":"
		out.RawString(prefix)
		if in.URL == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.URL))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PhotoInputDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson49c0357aEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PhotoInputDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson49c0357aEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PhotoInputDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson49c0357aDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PhotoInputDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson49c0357aDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(l, v)
}
func easyjson49c0357aDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(in *jlexer.Lexer, out *PhotoInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "FileHeader":
			if in.IsNull() {
				in.Skip()
				out.FileHeader = nil
			} else {
				if out.FileHeader == nil {
					out.FileHeader = new(FileInput)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.FileHeader).UnmarshalEasyJSON(in)
				}
			}
		case "Path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Path = string(in.String())
			}
		case "Order":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Order = int(in.Int())
			}
		case "URL":
			if in.IsNull() {
				in.Skip()
				out.URL = nil
			} else {
				if out.URL == nil {
					out.URL = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.URL = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson49c0357aEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(out *jwriter.Writer, in PhotoInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"FileHeader\":"
		out.RawString(prefix[1:])
		if in.FileHeader == nil {
			out.RawString("null")
		} else {
			(*in.FileHeader).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"Path\":"
		out.RawString(prefix)
		out.String(string(in.Path))
	}
	{
		const prefix string = ",\"Order\":"
		out.RawString(prefix)
		out.Int(int(in.Order))
	}
	{
		const prefix string = ",\"URL\":"
		out.RawString(prefix)
		if in.URL == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.URL))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PhotoInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson49c0357aEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PhotoInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson49c0357aEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PhotoInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson49c0357aDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PhotoInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson49c0357aDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(l, v)
}
func easyjson49c0357aDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(in *jlexer.Lexer, out *PhotoDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "img_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ImgURL = string(in.String())
			}
		case "order":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Order = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson49c0357aEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(out *jwriter.Writer, in PhotoDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"img_url\":"
		out.RawString(prefix[1:])
		out.String(string(in.ImgURL))
	}
	{
		const prefix string = ",\"order\":"
		out.RawString(prefix)
		out.Int(int(in.Order))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PhotoDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson49c0357aEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PhotoDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson49c0357aEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PhotoDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson49c0357aDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PhotoDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson49c0357aDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(l, v)
}
