// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	geo "github.com/go-park-mail-ru/2026_1_TheBugs/internal/utils/geo"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(in *jlexer.Lexer, out *PriceHistoryDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "date":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Date = string(in.String())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(out *jwriter.Writer, in PriceHistoryDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"date\":"
		out.RawString(prefix[1:])
		out.String(string(in.Date))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PriceHistoryDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PriceHistoryDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PriceHistoryDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PriceHistoryDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(l, v)
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(in *jlexer.Lexer, out *PostersResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "len":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Len = int(in.Int())
			}
		case "posters":
			if in.IsNull() {
				in.Skip()
				out.Posters = nil
			} else {
				in.Delim('[')
				if out.Posters == nil {
					if !in.IsDelim(']') {
						out.Posters = make([]PosterCardDTO, 0, 0)
					} else {
						out.Posters = []PosterCardDTO{}
					}
				} else {
					out.Posters = (out.Posters)[:0]
				}
				for !in.IsDelim(']') {
					var v1 PosterCardDTO
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Posters = append(out.Posters, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(out *jwriter.Writer, in PostersResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"len\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Len))
	}
	{
		const prefix string = ",\"posters\":"
		out.RawString(prefix)
		if in.Posters == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Posters {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PostersResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PostersResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PostersResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PostersResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(l, v)
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(in *jlexer.Lexer, out *PostersFiltersDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int(in.Int())
			}
		case "Offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int(in.Int())
			}
		case "SearchQuery":
			if in.IsNull() {
				in.Skip()
				out.SearchQuery = nil
			} else {
				if out.SearchQuery == nil {
					out.SearchQuery = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.SearchQuery = string(in.String())
				}
			}
		case "UtilityCompany":
			if in.IsNull() {
				in.Skip()
				out.UtilityCompany = nil
			} else {
				if out.UtilityCompany == nil {
					out.UtilityCompany = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.UtilityCompany = string(in.String())
				}
			}
		case "Category":
			if in.IsNull() {
				in.Skip()
				out.Category = nil
			} else {
				if out.Category == nil {
					out.Category = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Category = string(in.String())
				}
			}
		case "MaxPrice":
			if in.IsNull() {
				in.Skip()
				out.MaxPrice = nil
			} else {
				if out.MaxPrice == nil {
					out.MaxPrice = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.MaxPrice = int(in.Int())
				}
			}
		case "MinPrice":
			if in.IsNull() {
				in.Skip()
				out.MinPrice = nil
			} else {
				if out.MinPrice == nil {
					out.MinPrice = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.MinPrice = int(in.Int())
				}
			}
		case "RoomCount":
			if in.IsNull() {
				in.Skip()
				out.RoomCount = nil
			} else {
				if out.RoomCount == nil {
					out.RoomCount = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.RoomCount = int(in.Int())
				}
			}
		case "MaxSquare":
			if in.IsNull() {
				in.Skip()
				out.MaxSquare = nil
			} else {
				if out.MaxSquare == nil {
					out.MaxSquare = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.MaxSquare = int(in.Int())
				}
			}
		case "MinSquare":
			if in.IsNull() {
				in.Skip()
				out.MinSquare = nil
			} else {
				if out.MinSquare == nil {
					out.MinSquare = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.MinSquare = int(in.Int())
				}
			}
		case "Facilities":
			if in.IsNull() {
				in.Skip()
				out.Facilities = nil
			} else {
				in.Delim('[')
				if out.Facilities == nil {
					if !in.IsDelim(']') {
						out.Facilities = make([]string, 0, 4)
					} else {
						out.Facilities = []string{}
					}
				} else {
					out.Facilities = (out.Facilities)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					if in.IsNull() {
						in.Skip()
					} else {
						v4 = string(in.String())
					}
					out.Facilities = append(out.Facilities, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "MaxFlatFloor":
			if in.IsNull() {
				in.Skip()
				out.MaxFlatFloor = nil
			} else {
				if out.MaxFlatFloor == nil {
					out.MaxFlatFloor = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.MaxFlatFloor = int(in.Int())
				}
			}
		case "MinFlatFloor":
			if in.IsNull() {
				in.Skip()
				out.MinFlatFloor = nil
			} else {
				if out.MinFlatFloor == nil {
					out.MinFlatFloor = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.MinFlatFloor = int(in.Int())
				}
			}
		case "IsNotFirstFloor":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsNotFirstFloor = bool(in.Bool())
			}
		case "IsNotLastFloor":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsNotLastFloor = bool(in.Bool())
			}
		case "MaxBuildingFloor":
			if in.IsNull() {
				in.Skip()
				out.MaxBuildingFloor = nil
			} else {
				if out.MaxBuildingFloor == nil {
					out.MaxBuildingFloor = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.MaxBuildingFloor = int(in.Int())
				}
			}
		case "MinBuildingFloor":
			if in.IsNull() {
				in.Skip()
				out.MinBuildingFloor = nil
			} else {
				if out.MinBuildingFloor == nil {
					out.MinBuildingFloor = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.MinBuildingFloor = int(in.Int())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(out *jwriter.Writer, in PostersFiltersDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Limit\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Limit))
	}
	{
		const prefix string = ",\"Offset\":"
		out.RawString(prefix)
		out.Int(int(in.Offset))
	}
	{
		const prefix string = ",\"SearchQuery\":"
		out.RawString(prefix)
		if in.SearchQuery == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.SearchQuery))
		}
	}
	{
		const prefix string = ",\"UtilityCompany\":"
		out.RawString(prefix)
		if in.UtilityCompany == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.UtilityCompany))
		}
	}
	{
		const prefix string = ",\"Category\":"
		out.RawString(prefix)
		if in.Category == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Category))
		}
	}
	{
		const prefix string = ",\"MaxPrice\":"
		out.RawString(prefix)
		if in.MaxPrice == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.MaxPrice))
		}
	}
	{
		const prefix string = ",\"MinPrice\":"
		out.RawString(prefix)
		if in.MinPrice == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.MinPrice))
		}
	}
	{
		const prefix string = ",\"RoomCount\":"
		out.RawString(prefix)
		if in.RoomCount == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.RoomCount))
		}
	}
	{
		const prefix string = ",\"MaxSquare\":"
		out.RawString(prefix)
		if in.MaxSquare == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.MaxSquare))
		}
	}
	{
		const prefix string = ",\"MinSquare\":"
		out.RawString(prefix)
		if in.MinSquare == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.MinSquare))
		}
	}
	{
		const prefix string = ",\"Facilities\":"
		out.RawString(prefix)
		if in.Facilities == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Facilities {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"MaxFlatFloor\":"
		out.RawString(prefix)
		if in.MaxFlatFloor == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.MaxFlatFloor))
		}
	}
	{
		const prefix string = ",\"MinFlatFloor\":"
		out.RawString(prefix)
		if in.MinFlatFloor == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.MinFlatFloor))
		}
	}
	{
		const prefix string = ",\"IsNotFirstFloor\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsNotFirstFloor))
	}
	{
		const prefix string = ",\"IsNotLastFloor\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsNotLastFloor))
	}
	{
		const prefix string = ",\"MaxBuildingFloor\":"
		out.RawString(prefix)
		if in.MaxBuildingFloor == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.MaxBuildingFloor))
		}
	}
	{
		const prefix string = ",\"MinBuildingFloor\":"
		out.RawString(prefix)
		if in.MinBuildingFloor == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.MinBuildingFloor))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PostersFiltersDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PostersFiltersDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PostersFiltersDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PostersFiltersDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(l, v)
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(in *jlexer.Lexer, out *PosterUpdateIDs) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "UserID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int(in.Int())
			}
		case "PosterID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PosterID = int(in.Int())
			}
		case "PropertyID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PropertyID = int(in.Int())
			}
		case "BuildingID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BuildingID = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(out *jwriter.Writer, in PosterUpdateIDs) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"UserID\":"
		out.RawString(prefix[1:])
		out.Int(int(in.UserID))
	}
	{
		const prefix string = ",\"PosterID\":"
		out.RawString(prefix)
		out.Int(int(in.PosterID))
	}
	{
		const prefix string = ",\"PropertyID\":"
		out.RawString(prefix)
		out.Int(int(in.PropertyID))
	}
	{
		const prefix string = ",\"BuildingID\":"
		out.RawString(prefix)
		out.Int(int(in.BuildingID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PosterUpdateIDs) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PosterUpdateIDs) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PosterUpdateIDs) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PosterUpdateIDs) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(l, v)
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto4(in *jlexer.Lexer, out *PosterInputFlatDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "UserID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int(in.Int())
			}
		case "Alias":
			if in.IsNull() {
				in.Skip()
				out.Alias = nil
			} else {
				if out.Alias == nil {
					out.Alias = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Alias = string(in.String())
				}
			}
		case "Price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		case "Description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "CategoryAlias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CategoryAlias = string(in.String())
			}
		case "Area":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Area = float64(in.Float64())
			}
		case "GeoLat":
			if in.IsNull() {
				in.Skip()
			} else {
				out.GeoLat = float64(in.Float64())
			}
		case "GeoLon":
			if in.IsNull() {
				in.Skip()
			} else {
				out.GeoLon = float64(in.Float64())
			}
		case "FlatCategoryID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FlatCategoryID = int(in.Int())
			}
		case "FlatNumber":
			if in.IsNull() {
				in.Skip()
				out.FlatNumber = nil
			} else {
				if out.FlatNumber == nil {
					out.FlatNumber = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.FlatNumber = int(in.Int())
				}
			}
		case "FlatFloor":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FlatFloor = int(in.Int())
			}
		case "Address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "City":
			if in.IsNull() {
				in.Skip()
			} else {
				out.City = string(in.String())
			}
		case "District":
			if in.IsNull() {
				in.Skip()
				out.District = nil
			} else {
				if out.District == nil {
					out.District = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.District = string(in.String())
				}
			}
		case "FloorCount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FloorCount = int(in.Int())
			}
		case "CompanyID":
			if in.IsNull() {
				in.Skip()
				out.CompanyID = nil
			} else {
				if out.CompanyID == nil {
					out.CompanyID = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.CompanyID = int(in.Int())
				}
			}
		case "Features":
			if in.IsNull() {
				in.Skip()
				out.Features = nil
			} else {
				in.Delim('[')
				if out.Features == nil {
					if !in.IsDelim(']') {
						out.Features = make([]string, 0, 4)
					} else {
						out.Features = []string{}
					}
				} else {
					out.Features = (out.Features)[:0]
				}
				for !in.IsDelim(']') {
					var v7 string
					if in.IsNull() {
						in.Skip()
					} else {
						v7 = string(in.String())
					}
					out.Features = append(out.Features, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "Images":
			if in.IsNull() {
				in.Skip()
				out.Images = nil
			} else {
				in.Delim('[')
				if out.Images == nil {
					if !in.IsDelim(']') {
						out.Images = make([]PhotoInputDTO, 0, 2)
					} else {
						out.Images = []PhotoInputDTO{}
					}
				} else {
					out.Images = (out.Images)[:0]
				}
				for !in.IsDelim(']') {
					var v8 PhotoInputDTO
					if in.IsNull() {
						in.Skip()
					} else {
						(v8).UnmarshalEasyJSON(in)
					}
					out.Images = append(out.Images, v8)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto4(out *jwriter.Writer, in PosterInputFlatDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"UserID\":"
		out.RawString(prefix[1:])
		out.Int(int(in.UserID))
	}
	{
		const prefix string = ",\"Alias\":"
		out.RawString(prefix)
		if in.Alias == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Alias))
		}
	}
	{
		const prefix string = ",\"Price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"Description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"CategoryAlias\":"
		out.RawString(prefix)
		out.String(string(in.CategoryAlias))
	}
	{
		const prefix string = ",\"Area\":"
		out.RawString(prefix)
		out.Float64(float64(in.Area))
	}
	{
		const prefix string = ",\"GeoLat\":"
		out.RawString(prefix)
		out.Float64(float64(in.GeoLat))
	}
	{
		const prefix string = ",\"GeoLon\":"
		out.RawString(prefix)
		out.Float64(float64(in.GeoLon))
	}
	{
		const prefix string = ",\"FlatCategoryID\":"
		out.RawString(prefix)
		out.Int(int(in.FlatCategoryID))
	}
	{
		const prefix string = ",\"FlatNumber\":"
		out.RawString(prefix)
		if in.FlatNumber == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.FlatNumber))
		}
	}
	{
		const prefix string = ",\"FlatFloor\":"
		out.RawString(prefix)
		out.Int(int(in.FlatFloor))
	}
	{
		const prefix string = ",\"Address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"City\":"
		out.RawString(prefix)
		out.String(string(in.City))
	}
	{
		const prefix string = ",\"District\":"
		out.RawString(prefix)
		if in.District == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.District))
		}
	}
	{
		const prefix string = ",\"FloorCount\":"
		out.RawString(prefix)
		out.Int(int(in.FloorCount))
	}
	{
		const prefix string = ",\"CompanyID\":"
		out.RawString(prefix)
		if in.CompanyID == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.CompanyID))
		}
	}
	{
		const prefix string = ",\"Features\":"
		out.RawString(prefix)
		if in.Features == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v9, v10 := range in.Features {
				if v9 > 0 {
					out.RawByte(',')
				}
				out.String(string(v10))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"Images\":"
		out.RawString(prefix)
		if in.Images == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.Images {
				if v11 > 0 {
					out.RawByte(',')
				}
				(v12).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PosterInputFlatDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PosterInputFlatDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PosterInputFlatDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PosterInputFlatDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto4(l, v)
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto5(in *jlexer.Lexer, out *PosterInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "UserID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int(in.Int())
			}
		case "Alias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alias = string(in.String())
			}
		case "Price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		case "Description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "CategoryAlias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CategoryAlias = string(in.String())
			}
		case "Area":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Area = float64(in.Float64())
			}
		case "Address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "Geo":
			easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUtilsGeo(in, &out.Geo)
		case "CityID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CityID = int(in.Int())
			}
		case "MetroStationID":
			if in.IsNull() {
				in.Skip()
				out.MetroStationID = nil
			} else {
				if out.MetroStationID == nil {
					out.MetroStationID = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.MetroStationID = int(in.Int())
				}
			}
		case "District":
			if in.IsNull() {
				in.Skip()
				out.District = nil
			} else {
				if out.District == nil {
					out.District = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.District = string(in.String())
				}
			}
		case "FloorCount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FloorCount = int(in.Int())
			}
		case "CompanyID":
			if in.IsNull() {
				in.Skip()
				out.CompanyID = nil
			} else {
				if out.CompanyID == nil {
					out.CompanyID = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.CompanyID = int(in.Int())
				}
			}
		case "Features":
			if in.IsNull() {
				in.Skip()
				out.Features = nil
			} else {
				in.Delim('[')
				if out.Features == nil {
					if !in.IsDelim(']') {
						out.Features = make([]string, 0, 4)
					} else {
						out.Features = []string{}
					}
				} else {
					out.Features = (out.Features)[:0]
				}
				for !in.IsDelim(']') {
					var v13 string
					if in.IsNull() {
						in.Skip()
					} else {
						v13 = string(in.String())
					}
					out.Features = append(out.Features, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "Images":
			if in.IsNull() {
				in.Skip()
				out.Images = nil
			} else {
				in.Delim('[')
				if out.Images == nil {
					if !in.IsDelim(']') {
						out.Images = make([]PhotoInput, 0, 1)
					} else {
						out.Images = []PhotoInput{}
					}
				} else {
					out.Images = (out.Images)[:0]
				}
				for !in.IsDelim(']') {
					var v14 PhotoInput
					if in.IsNull() {
						in.Skip()
					} else {
						(v14).UnmarshalEasyJSON(in)
					}
					out.Images = append(out.Images, v14)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto5(out *jwriter.Writer, in PosterInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"UserID\":"
		out.RawString(prefix[1:])
		out.Int(int(in.UserID))
	}
	{
		const prefix string = ",\"Alias\":"
		out.RawString(prefix)
		out.String(string(in.Alias))
	}
	{
		const prefix string = ",\"Price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"Description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"CategoryAlias\":"
		out.RawString(prefix)
		out.String(string(in.CategoryAlias))
	}
	{
		const prefix string = ",\"Area\":"
		out.RawString(prefix)
		out.Float64(float64(in.Area))
	}
	{
		const prefix string = ",\"Address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"Geo\":"
		out.RawString(prefix)
		easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUtilsGeo(out, in.Geo)
	}
	{
		const prefix string = ",\"CityID\":"
		out.RawString(prefix)
		out.Int(int(in.CityID))
	}
	{
		const prefix string = ",\"MetroStationID\":"
		out.RawString(prefix)
		if in.MetroStationID == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.MetroStationID))
		}
	}
	{
		const prefix string = ",\"District\":"
		out.RawString(prefix)
		if in.District == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.District))
		}
	}
	{
		const prefix string = ",\"FloorCount\":"
		out.RawString(prefix)
		out.Int(int(in.FloorCount))
	}
	{
		const prefix string = ",\"CompanyID\":"
		out.RawString(prefix)
		if in.CompanyID == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.CompanyID))
		}
	}
	{
		const prefix string = ",\"Features\":"
		out.RawString(prefix)
		if in.Features == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v15, v16 := range in.Features {
				if v15 > 0 {
					out.RawByte(',')
				}
				out.String(string(v16))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"Images\":"
		out.RawString(prefix)
		if in.Images == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v17, v18 := range in.Images {
				if v17 > 0 {
					out.RawByte(',')
				}
				(v18).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PosterInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PosterInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PosterInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PosterInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto5(l, v)
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUtilsGeo(in *jlexer.Lexer, out *geo.GeographyPoint) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Lat":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Lat = float64(in.Float64())
			}
		case "Lon":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Lon = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUtilsGeo(out *jwriter.Writer, in geo.GeographyPoint) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Lat\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.Lat))
	}
	{
		const prefix string = ",\"Lon\":"
		out.RawString(prefix)
		out.Float64(float64(in.Lon))
	}
	out.RawByte('}')
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto6(in *jlexer.Lexer, out *PosterDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int(in.Int())
			}
		case "alias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alias = string(in.String())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		case "category":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Category).UnmarshalEasyJSON(in)
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "area":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Area = float64(in.Float64())
			}
		case "building_geo":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Geo).UnmarshalEasyJSON(in)
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "district":
			if in.IsNull() {
				in.Skip()
				out.District = nil
			} else {
				if out.District == nil {
					out.District = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.District = string(in.String())
				}
			}
		case "metro":
			if in.IsNull() {
				in.Skip()
				out.Metro = nil
			} else {
				if out.Metro == nil {
					out.Metro = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Metro = string(in.String())
				}
			}
		case "metro_geo":
			if in.IsNull() {
				in.Skip()
				out.MetroGeo = nil
			} else {
				if out.MetroGeo == nil {
					out.MetroGeo = new(GeographyDTO)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.MetroGeo).UnmarshalEasyJSON(in)
				}
			}
		case "city":
			if in.IsNull() {
				in.Skip()
			} else {
				out.City = string(in.String())
			}
		case "floor_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FloorCount = int(in.Int())
			}
		case "images":
			if in.IsNull() {
				in.Skip()
				out.Images = nil
			} else {
				in.Delim('[')
				if out.Images == nil {
					if !in.IsDelim(']') {
						out.Images = make([]PhotoDTO, 0, 2)
					} else {
						out.Images = []PhotoDTO{}
					}
				} else {
					out.Images = (out.Images)[:0]
				}
				for !in.IsDelim(']') {
					var v19 PhotoDTO
					if in.IsNull() {
						in.Skip()
					} else {
						(v19).UnmarshalEasyJSON(in)
					}
					out.Images = append(out.Images, v19)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "seller":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Seller).UnmarshalEasyJSON(in)
			}
		case "flat":
			if in.IsNull() {
				in.Skip()
				out.Flat = nil
			} else {
				if out.Flat == nil {
					out.Flat = new(FlatDTO)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Flat).UnmarshalEasyJSON(in)
				}
			}
		case "house":
			if in.IsNull() {
				in.Skip()
				out.House = nil
			} else {
				if out.House == nil {
					out.House = new(HouseDTO)
				}
				easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto7(in, out.House)
			}
		case "facilities":
			if in.IsNull() {
				in.Skip()
				out.Facilities = nil
			} else {
				in.Delim('[')
				if out.Facilities == nil {
					if !in.IsDelim(']') {
						out.Facilities = make([]FacilityDTO, 0, 2)
					} else {
						out.Facilities = []FacilityDTO{}
					}
				} else {
					out.Facilities = (out.Facilities)[:0]
				}
				for !in.IsDelim(']') {
					var v20 FacilityDTO
					if in.IsNull() {
						in.Skip()
					} else {
						(v20).UnmarshalEasyJSON(in)
					}
					out.Facilities = append(out.Facilities, v20)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "company":
			if in.IsNull() {
				in.Skip()
				out.Company = nil
			} else {
				if out.Company == nil {
					out.Company = new(UtilityCompanyCardDTO)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Company).UnmarshalEasyJSON(in)
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto6(out *jwriter.Writer, in PosterDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix)
		out.String(string(in.Alias))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		(in.Category).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"area\":"
		out.RawString(prefix)
		out.Float64(float64(in.Area))
	}
	{
		const prefix string = ",\"building_geo\":"
		out.RawString(prefix)
		(in.Geo).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"district\":"
		out.RawString(prefix)
		if in.District == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.District))
		}
	}
	{
		const prefix string = ",\"metro\":"
		out.RawString(prefix)
		if in.Metro == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Metro))
		}
	}
	{
		const prefix string = ",\"metro_geo\":"
		out.RawString(prefix)
		if in.MetroGeo == nil {
			out.RawString("null")
		} else {
			(*in.MetroGeo).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"city\":"
		out.RawString(prefix)
		out.String(string(in.City))
	}
	{
		const prefix string = ",\"floor_count\":"
		out.RawString(prefix)
		out.Int(int(in.FloorCount))
	}
	{
		const prefix string = ",\"images\":"
		out.RawString(prefix)
		if in.Images == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v21, v22 := range in.Images {
				if v21 > 0 {
					out.RawByte(',')
				}
				(v22).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"seller\":"
		out.RawString(prefix)
		(in.Seller).MarshalEasyJSON(out)
	}
	if in.Flat != nil {
		const prefix string = ",\"flat\":"
		out.RawString(prefix)
		(*in.Flat).MarshalEasyJSON(out)
	}
	if in.House != nil {
		const prefix string = ",\"house\":"
		out.RawString(prefix)
		easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto7(out, *in.House)
	}
	{
		const prefix string = ",\"facilities\":"
		out.RawString(prefix)
		if in.Facilities == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v23, v24 := range in.Facilities {
				if v23 > 0 {
					out.RawByte(',')
				}
				(v24).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.Company != nil {
		const prefix string = ",\"company\":"
		out.RawString(prefix)
		(*in.Company).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PosterDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PosterDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PosterDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PosterDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto6(l, v)
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto7(in *jlexer.Lexer, out *HouseDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto7(out *jwriter.Writer, in HouseDTO) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto8(in *jlexer.Lexer, out *PosterCardDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int(in.Int())
			}
		case "alias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alias = string(in.String())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		case "imageUrl":
			if in.IsNull() {
				in.Skip()
				out.ImgURL = nil
			} else {
				if out.ImgURL == nil {
					out.ImgURL = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ImgURL = string(in.String())
				}
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "metro":
			if in.IsNull() {
				in.Skip()
				out.Metro = nil
			} else {
				if out.Metro == nil {
					out.Metro = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Metro = string(in.String())
				}
			}
		case "area":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Area = float64(in.Float64())
			}
		case "flat_category":
			if in.IsNull() {
				in.Skip()
				out.FlatCategory = nil
			} else {
				if out.FlatCategory == nil {
					out.FlatCategory = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.FlatCategory = string(in.String())
				}
			}
		case "has_active_promotion":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HasActivePromotion = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto8(out *jwriter.Writer, in PosterCardDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix)
		out.String(string(in.Alias))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"imageUrl\":"
		out.RawString(prefix)
		if in.ImgURL == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.ImgURL))
		}
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"metro\":"
		out.RawString(prefix)
		if in.Metro == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Metro))
		}
	}
	{
		const prefix string = ",\"area\":"
		out.RawString(prefix)
		out.Float64(float64(in.Area))
	}
	{
		const prefix string = ",\"flat_category\":"
		out.RawString(prefix)
		if in.FlatCategory == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.FlatCategory))
		}
	}
	{
		const prefix string = ",\"has_active_promotion\":"
		out.RawString(prefix)
		out.Bool(bool(in.HasActivePromotion))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PosterCardDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PosterCardDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PosterCardDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PosterCardDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto8(l, v)
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto9(in *jlexer.Lexer, out *MyPosterDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int(in.Int())
			}
		case "alias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alias = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "area":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Area = float64(in.Float64())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float64(in.Float64())
			}
		case "avatar_url":
			if in.IsNull() {
				in.Skip()
				out.AvatarURl = nil
			} else {
				if out.AvatarURl == nil {
					out.AvatarURl = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.AvatarURl = string(in.String())
				}
			}
		case "category":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Category).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto9(out *jwriter.Writer, in MyPosterDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix)
		out.String(string(in.Alias))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"area\":"
		out.RawString(prefix)
		out.Float64(float64(in.Area))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	{
		const prefix string = ",\"avatar_url\":"
		out.RawString(prefix)
		if in.AvatarURl == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.AvatarURl))
		}
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		(in.Category).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MyPosterDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MyPosterDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MyPosterDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MyPosterDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto9(l, v)
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto10(in *jlexer.Lexer, out *Geometry) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "coordinates":
			if in.IsNull() {
				in.Skip()
				out.Coordinates = nil
			} else {
				in.Delim('[')
				if out.Coordinates == nil {
					if !in.IsDelim(']') {
						out.Coordinates = make([]float64, 0, 8)
					} else {
						out.Coordinates = []float64{}
					}
				} else {
					out.Coordinates = (out.Coordinates)[:0]
				}
				for !in.IsDelim(']') {
					var v25 float64
					if in.IsNull() {
						in.Skip()
					} else {
						v25 = float64(in.Float64())
					}
					out.Coordinates = append(out.Coordinates, v25)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto10(out *jwriter.Writer, in Geometry) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"coordinates\":"
		out.RawString(prefix)
		if in.Coordinates == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v26, v27 := range in.Coordinates {
				if v26 > 0 {
					out.RawByte(',')
				}
				out.Float64(float64(v27))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Geometry) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Geometry) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Geometry) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Geometry) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto10(l, v)
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto11(in *jlexer.Lexer, out *GeoJSONFeatureResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "features":
			if in.IsNull() {
				in.Skip()
				out.Posters = nil
			} else {
				in.Delim('[')
				if out.Posters == nil {
					if !in.IsDelim(']') {
						out.Posters = make([]GeoJSONFeature, 0, 1)
					} else {
						out.Posters = []GeoJSONFeature{}
					}
				} else {
					out.Posters = (out.Posters)[:0]
				}
				for !in.IsDelim(']') {
					var v28 GeoJSONFeature
					if in.IsNull() {
						in.Skip()
					} else {
						(v28).UnmarshalEasyJSON(in)
					}
					out.Posters = append(out.Posters, v28)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "len":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Len = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto11(out *jwriter.Writer, in GeoJSONFeatureResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"features\":"
		out.RawString(prefix[1:])
		if in.Posters == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v29, v30 := range in.Posters {
				if v29 > 0 {
					out.RawByte(',')
				}
				(v30).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"len\":"
		out.RawString(prefix)
		out.Int(int(in.Len))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GeoJSONFeatureResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GeoJSONFeatureResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GeoJSONFeatureResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GeoJSONFeatureResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto11(l, v)
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto12(in *jlexer.Lexer, out *GeoJSONFeature) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "propertiese":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Properties = make(map[string]interface{})
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v31 interface{}
					if m, ok := v31.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v31.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v31 = in.Interface()
					}
					(out.Properties)[key] = v31
					in.WantComma()
				}
				in.Delim('}')
			}
		case "geometry":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Geometry).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto12(out *jwriter.Writer, in GeoJSONFeature) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"propertiese\":"
		out.RawString(prefix)
		if in.Properties == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v32First := true
			for v32Name, v32Value := range in.Properties {
				if v32First {
					v32First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v32Name))
				out.RawByte(':')
				if m, ok := v32Value.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v32Value.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v32Value))
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"geometry\":"
		out.RawString(prefix)
		(in.Geometry).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GeoJSONFeature) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GeoJSONFeature) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GeoJSONFeature) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GeoJSONFeature) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto12(l, v)
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto13(in *jlexer.Lexer, out *GenerateDescriptionDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "category":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Category = string(in.String())
			}
		case "area":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Area = float64(in.Float64())
			}
		case "flat_category":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FlatCategory = string(in.String())
			}
		case "city":
			if in.IsNull() {
				in.Skip()
			} else {
				out.City = string(in.String())
			}
		case "features":
			if in.IsNull() {
				in.Skip()
				out.Features = nil
			} else {
				in.Delim('[')
				if out.Features == nil {
					if !in.IsDelim(']') {
						out.Features = make([]string, 0, 4)
					} else {
						out.Features = []string{}
					}
				} else {
					out.Features = (out.Features)[:0]
				}
				for !in.IsDelim(']') {
					var v33 string
					if in.IsNull() {
						in.Skip()
					} else {
						v33 = string(in.String())
					}
					out.Features = append(out.Features, v33)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto13(out *jwriter.Writer, in GenerateDescriptionDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix[1:])
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"area\":"
		out.RawString(prefix)
		out.Float64(float64(in.Area))
	}
	{
		const prefix string = ",\"flat_category\":"
		out.RawString(prefix)
		out.String(string(in.FlatCategory))
	}
	{
		const prefix string = ",\"city\":"
		out.RawString(prefix)
		out.String(string(in.City))
	}
	{
		const prefix string = ",\"features\":"
		out.RawString(prefix)
		if in.Features == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v34, v35 := range in.Features {
				if v34 > 0 {
					out.RawByte(',')
				}
				out.String(string(v35))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GenerateDescriptionDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GenerateDescriptionDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GenerateDescriptionDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GenerateDescriptionDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto13(l, v)
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto14(in *jlexer.Lexer, out *CreatedPoster) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int(in.Int())
			}
		case "alias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alias = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto14(out *jwriter.Writer, in CreatedPoster) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix)
		out.String(string(in.Alias))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreatedPoster) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto14(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreatedPoster) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto14(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreatedPoster) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto14(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreatedPoster) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto14(l, v)
}
func easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto15(in *jlexer.Lexer, out *CategoryDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "alias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alias = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto15(out *jwriter.Writer, in CategoryDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix)
		out.String(string(in.Alias))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CategoryDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto15(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CategoryDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e67580bEncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto15(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CategoryDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto15(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CategoryDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e67580bDecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto15(l, v)
}
