// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonDad19f25DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(in *jlexer.Lexer, out *UserPromotionsDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "lenght":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Lenght = int(in.Int())
			}
		case "promotions":
			if in.IsNull() {
				in.Skip()
				out.Promotions = nil
			} else {
				in.Delim('[')
				if out.Promotions == nil {
					if !in.IsDelim(']') {
						out.Promotions = make([]UserPromotionDTO, 0, 1)
					} else {
						out.Promotions = []UserPromotionDTO{}
					}
				} else {
					out.Promotions = (out.Promotions)[:0]
				}
				for !in.IsDelim(']') {
					var v1 UserPromotionDTO
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Promotions = append(out.Promotions, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDad19f25EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(out *jwriter.Writer, in UserPromotionsDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"lenght\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Lenght))
	}
	{
		const prefix string = ",\"promotions\":"
		out.RawString(prefix)
		if in.Promotions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Promotions {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserPromotionsDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDad19f25EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserPromotionsDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDad19f25EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserPromotionsDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDad19f25DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserPromotionsDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDad19f25DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(l, v)
}
func easyjsonDad19f25DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(in *jlexer.Lexer, out *UserPromotionDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "promotion_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PromotionID = int(in.Int())
			}
		case "ends_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.EndsAt).UnmarshalJSON(data))
				}
			}
		case "poster_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PosterID = int(in.Int())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDad19f25EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(out *jwriter.Writer, in UserPromotionDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"promotion_id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.PromotionID))
	}
	{
		const prefix string = ",\"ends_at\":"
		out.RawString(prefix)
		out.Raw((in.EndsAt).MarshalJSON())
	}
	{
		const prefix string = ",\"poster_id\":"
		out.RawString(prefix)
		out.Int(int(in.PosterID))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserPromotionDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDad19f25EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserPromotionDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDad19f25EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserPromotionDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDad19f25DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserPromotionDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDad19f25DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto1(l, v)
}
func easyjsonDad19f25DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(in *jlexer.Lexer, out *PromotionDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int(in.Int())
			}
		case "Code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "Price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = float32(in.Float32())
			}
		case "DurationDays":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DurationDays = int(in.Int())
			}
		case "Name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "Description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDad19f25EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(out *jwriter.Writer, in PromotionDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"Code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"Price\":"
		out.RawString(prefix)
		out.Float32(float32(in.Price))
	}
	{
		const prefix string = ",\"DurationDays\":"
		out.RawString(prefix)
		out.Int(int(in.DurationDays))
	}
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"Description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PromotionDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDad19f25EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PromotionDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDad19f25EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PromotionDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDad19f25DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PromotionDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDad19f25DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto2(l, v)
}
func easyjsonDad19f25DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(in *jlexer.Lexer, out *CreatePromotionDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "PosterID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PosterID = int(in.Int())
			}
		case "UserID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int(in.Int())
			}
		case "PromotionCode":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PromotionCode = string(in.String())
			}
		case "PaymentID":
			if in.IsNull() {
				in.Skip()
				out.PaymentID = nil
			} else {
				if out.PaymentID == nil {
					out.PaymentID = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.PaymentID = string(in.String())
				}
			}
		case "EndsAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.EndsAt).UnmarshalJSON(data))
				}
			}
		case "AmountPaid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AmountPaid = float32(in.Float32())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDad19f25EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(out *jwriter.Writer, in CreatePromotionDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"PosterID\":"
		out.RawString(prefix[1:])
		out.Int(int(in.PosterID))
	}
	{
		const prefix string = ",\"UserID\":"
		out.RawString(prefix)
		out.Int(int(in.UserID))
	}
	{
		const prefix string = ",\"PromotionCode\":"
		out.RawString(prefix)
		out.String(string(in.PromotionCode))
	}
	{
		const prefix string = ",\"PaymentID\":"
		out.RawString(prefix)
		if in.PaymentID == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.PaymentID))
		}
	}
	{
		const prefix string = ",\"EndsAt\":"
		out.RawString(prefix)
		out.Raw((in.EndsAt).MarshalJSON())
	}
	{
		const prefix string = ",\"AmountPaid\":"
		out.RawString(prefix)
		out.Float32(float32(in.AmountPaid))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreatePromotionDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDad19f25EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreatePromotionDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDad19f25EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreatePromotionDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDad19f25DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreatePromotionDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDad19f25DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto3(l, v)
}
