// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonFcb26af1DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(in *jlexer.Lexer, out *PosterSellerDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "first_name":
			out.SellerFirstName = string(in.String())
		case "last_name":
			out.SellerLastName = string(in.String())
		case "phone":
			out.SellerPhone = string(in.String())
		case "avatar_url":
			if in.IsNull() {
				in.Skip()
				out.SellerAvatarURL = nil
			} else {
				if out.SellerAvatarURL == nil {
					out.SellerAvatarURL = new(string)
				}
				*out.SellerAvatarURL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFcb26af1EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(out *jwriter.Writer, in PosterSellerDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"first_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.SellerFirstName))
	}
	{
		const prefix string = ",\"last_name\":"
		out.RawString(prefix)
		out.String(string(in.SellerLastName))
	}
	{
		const prefix string = ",\"phone\":"
		out.RawString(prefix)
		out.String(string(in.SellerPhone))
	}
	{
		const prefix string = ",\"avatar_url\":"
		out.RawString(prefix)
		if in.SellerAvatarURL == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.SellerAvatarURL))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PosterSellerDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFcb26af1EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PosterSellerDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFcb26af1EncodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PosterSellerDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFcb26af1DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PosterSellerDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFcb26af1DecodeGithubComGoParkMailRu20261TheBugsInternalUsecaseDto(l, v)
}
