input {
  jdbc {
    jdbc_connection_string => "jdbc:postgresql://postgres:5432/main"
    jdbc_user => "thebugs"
    jdbc_password => "thebugs"
    jdbc_driver_library => "/usr/share/logstash/drivers/postgresql.jar"
    jdbc_driver_class => "org.postgresql.Driver"

    statement => "
        SELECT p.id, p.price, p.description, p.avatar_url,
               b.address, m.station_name, prop.area, f.floor, 
               p.alias, fc.name AS flat_category, c.city_name as city, 
               b.district, uc.alias AS company_alias, uc.company_name, p.updated_at, p.deleted_at
        FROM posters p
        LEFT JOIN property prop ON prop.id = p.property_id
        LEFT JOIN property_categories pc ON pc.id = prop.category_id
        LEFT JOIN buildings b ON b.id = prop.building_id
        LEFT JOIN cities c ON c.id = b.city_id
        LEFT JOIN metro_stations m ON b.metro_station_id = m.id
		    LEFT JOIN flat f ON f.property_id = prop.id
		    LEFT JOIN flat_categories fc ON fc.id = f.category_id
        LEFT JOIN utility_companies uc ON uc.id = b.company_id
        WHERE p.updated_at > :sql_last_value 
        ORDER BY updated_at ASC
    "

    use_column_value => true
    tracking_column => "updated_at"
    tracking_column_type => "timestamp"

    schedule => "* * * * *"
    clean_run => false
  }
}

filter {
  if [deleted_at] and [deleted_at] != "NULL" {
    mutate {
      add_field => { "[@metadata][elasticsearch_action]" => "delete" }
    }
    prune {
        whitelist_names => [ "id" ]
    }
  } else {
    mutate {
      add_field => { "[@metadata][elasticsearch_action]" => "index" }
      remove_field => [ "deleted_at" ]
    }
  }
  
  mutate {
    remove_field => [ "@version", "updated_at" ]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "id"
    action => "%{[@metadata][elasticsearch_action]}"
    document_id => "%{id}"
  }
  stdout { codec => rubydebug }
}