input {
  jdbc {
    jdbc_connection_string => "jdbc:postgresql://postgres:5432/main"
    jdbc_user => "thebugs"
    jdbc_password => "thebugs"
    jdbc_driver_library => "/usr/share/logstash/drivers/postgresql.jar"
    jdbc_driver_class => "org.postgresql.Driver"


    statement => "
        SELECT p.id, p.price, p.description, p.avatar_url, ST_X(b.geo::geometry) AS geo_lon, ST_Y(b.geo::geometry) AS geo_lat,
               b.floor_count AS building_floor, b.address, m.station_name, prop.area, f.floor, pc.name AS category_name, pc.alias AS category_alias,
               p.alias, fc.name AS flat_category, fc.room_count, c.city_name AS city,
               b.district, uc.alias AS company_alias, uc.company_name,
               COALESCE(
                  (SELECT json_agg(
                    json_build_object(
                      'id', fp.facility_id,
                      'name', f.name,
                      'alias', f.alias
                    )
                  ) 
                  FROM facility_property fp 
                  LEFT JOIN facilities f ON fp.facility_id = f.id 
                  WHERE fp.property_id = prop.id
                  ), '[]'::json
              )::TEXT AS facilities,
              p.updated_at, p.deleted_at
        FROM posters p
        LEFT JOIN property prop ON prop.id = p.property_id
        LEFT JOIN property_categories pc ON pc.id = prop.category_id
        LEFT JOIN buildings b ON b.id = prop.building_id
        LEFT JOIN cities c ON c.id = b.city_id
        LEFT JOIN metro_stations m ON b.metro_station_id = m.id
		    LEFT JOIN flat f ON f.property_id = prop.id
		    LEFT JOIN flat_categories fc ON fc.id = f.category_id
        LEFT JOIN utility_companies uc ON uc.id = b.company_id
        WHERE p.updated_at > :sql_last_value 
        ORDER BY updated_at ASC
    "

    use_column_value => true
    tracking_column => "updated_at"
    tracking_column_type => "timestamp"

    schedule => "*/5 * * * *"
    clean_run => false
  }
}

filter {
  json { 
    source => "facilities" 
    target => "facilities" 
  }
  if [geo_lon] and [geo_lat] {
    mutate {
      add_field => { "geo" => "%{[geo_lat]},%{[geo_lon]}" }
      remove_field => [ "geo_lon", "geo_lat" ]
    }
  }
  if [deleted_at] and [deleted_at] != "NULL" {
    mutate {
      add_field => { "[@metadata][elasticsearch_action]" => "delete" }
    }
    prune {
        whitelist_names => [ "id" ]
    }
  } else {
    mutate {
      add_field => { "[@metadata][elasticsearch_action]" => "index" }
      remove_field => [ "deleted_at" ]
    }
  }
  
  mutate {
    remove_field => [ "@version", "updated_at" ]
  }
}
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "posters"
    action => "%{[@metadata][elasticsearch_action]}"
    document_id => "%{id}"
  }
}